### ISSUE TITLE
Parsing of dates not working

### ISSUE THREAD

**Issue by phatthinh123** [ozlerhakan/poiji#10]
When i'm trying to parse date it turn out this format
I don't know why its not working with cell date types in my case 
instead of dd/M/yyyy it should be 
i tried to use cell.getDateCellValue() it will turn out the year will not missing
![image](https://user-images.githubusercontent.com/23252545/32070692-6101b60e-bab7-11e7-9100-414d06eb34d7.png)
![image](https://user-images.githubusercontent.com/23252545/32070721-71e99f72-bab7-11e7-8f1b-08b70e8fcf93.png)
![image](https://user-images.githubusercontent.com/23252545/32071011-276cf916-bab8-11e7-80ae-3139fd76cb9f.png)
here is the sample file
[Sample.zip](https://github.com/ozlerhakan/poiji/files/1419687/Sample.zip)

**Comment by ozlerhakan** [comment]
Hi @phatthinh123 ,

Did you try to change the default format of date using the poiji option?

```
public class Dates {

    @ExcelCell(1)
    private Date date;

    @Override
    public String toString() {
        return "DatePoiji{" +
                "date=" + date +
                '}';
    }

    public static void main(String[] args) {
        PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings().datePattern("dd/mm/yy").build();
        List<Dates> datePoijis = Poiji.fromExcel(new File("src/main/resources/Sample.xls"), Dates.class, options);

        System.out.println(datePoijis);
    }
}

```

Result:

```
[DatePoiji{date=Sun Jan 10 00:11:00 EET 2016}, DatePoiji{date=Wed Jan 06 00:30:00 EET 2016}, 
DatePoiji{date=Wed Jan 06 00:21:00 EET 2016}, DatePoiji{date=Wed Jan 06 00:16:00 EET 2016}, 
DatePoiji{date=Wed Jan 06 00:07:00 EET 2016}, DatePoiji{date=Sat Jan 02 00:01:00 EET 2016}, 
DatePoiji{date=Fri Jan 01 00:05:00 EET 2016}, DatePoiji{date=Sat Jan 10 00:14:00 EET 2015}, 
DatePoiji{date=Fri Jan 09 00:04:00 EET 2015}, DatePoiji{date=Thu Jan 08 00:04:00 EET 2015}, 
DatePoiji{date=Tue Jan 06 00:01:00 EET 2015}, DatePoiji{date=Mon Jan 05 00:29:00 EET 2015}, 
DatePoiji{date=Thu Jan 01 00:27:00 EET 2015}, DatePoiji{date=Thu Jan 01 00:13:00 EET 2015}, 
DatePoiji{date=Tue Jan 07 00:31:00 EET 2014}, DatePoiji{date=Tue Jan 07 00:11:00 EET 2014},.....]
```

**Comment by phatthinh123** [comment]
Oh, thanks you i didn't see that coming 
i was tried M/dd/yy

**Comment by dellikilari** [comment]
> Oh, thanks you i didn't see that coming
> i was tried M/dd/yy

Hi,
Am having the same problem, date is not properly converting.
below are the dates in xlxs file.
5/22/2019
5/24/2019
8/11/2019
And code is below.
		PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings().datePattern("dd/mm/yy").build();
		List<User> projectionVos = Poiji.fromExcel(inputStream, PoijiExcelType.XLSX, User.class, options);

results:
Wed Jan 16 00:02:00 IST 2019
Thu Jan 17 00:04:00 IST 2019
Fri Jan 18 00:11:00 IST 2019

Not sure why its converting to different month and day all together.

Thanks,
Delli/
