### ISSUE TITLE
columnToField maps not being utilized in current master

### ISSUE THREAD

**Issue by jigarWala** [ozlerhakan/poiji#105]
We could return from [here](https://github.com/ozlerhakan/poiji/blob/master/src/main/java/com/poiji/bind/mapping/PoijiHandler.java#L104) If we know `valueSet` is already true But currently it's not the case. and this makes column map useless.

**Comment by jigarWala** [comment]
we should also return `true` from [here](https://github.com/ozlerhakan/poiji/blob/master/src/main/java/com/poiji/bind/mapping/PoijiHandler.java#L141) if we know field is set

**Comment by thiyagu-7** [comment]
Thanks for taking care of this. This behavior was inadvertently changed when intenting to loop through all fields.

I guess, we need to return if we enter inside [this if](https://github.com/ozlerhakan/poiji/blob/master/src/main/java/com/poiji/bind/mapping/PoijiHandler.java#L91) block (not only when `valueSet` is true)

It should look like

    if(columnToField.containsKey(column)) {
        Field field = columnToField.get(column);
        if (columnToSuperClassField.containsKey(column)) {
            Object ins = null;
            ins = getInstance(columnToSuperClassField.get(column));
             if (setValue(field, column, content, ins)) {
                setFieldData(columnToSuperClassField.get(column), ins, instance);
                valueSet = true;
            }
        } else {
            valueSet = setValue(field, column, content, instance);
        }
         return valueSet; //<-- here
    }

Well, looking at this, it seems we need  the`valueSet` boolean only inside the *for* loop at line 104
https://github.com/ozlerhakan/poiji/blob/a98e4495c00b4b3d479ae46cba25354611cd8f65/src/main/java/com/poiji/bind/mapping/PoijiHandler.java#L104

Isn't the fix just as simple as above - just adding a return (and we can move the boolean only for the *for* loop at line 104 and make the return inline).

**Comment by jigarWala** [comment]
> I guess, we need to return if we enter inside this if block (not only when valueSet is true)

Ahh yes, true, inside  this if block `valueSet`  will always be true. I'll change this behavior in #106  

and about  the change in `setValue` function  it will scan other fields column index(if column name then from title map) in one scan which will be more efficient.

**Comment by jigarWala** [comment]
> Isn't the fix just as simple as above - just adding a return (and we can move the boolean only for the for loop at line 104 and make the return inline from the block before line 104).

yes, I'll patch it.

> and about the change in setValue function it will scan other fields column index(if column name then from title map) in one scan which will be more efficient.

I felt this change compliment well with this issue thus accommodating it in the #106  and not creating new one.

**Comment by thiyagu-7** [comment]
> yes, I'll patch it.

Thanks.

>and about the change in setValue function it will scan other fields column index(if column name then from title map) in one scan which will be more efficient.

I did not look in depth on the implications of this. Go ahead as you see fit

**Comment by jigarWala** [comment]
> Thanks.

done :+1: 

> I did not look in depth on the implications of this. Go ahead as you see fit

Well I haven't found any test that will prove this wrong. If you find please let me know :smile: 

The change inside `setValue(Field field, int column, String content, Object ins)` read all the column's annotation (ExcelCell/ExcelCellName) that poiji want's to read in one scan. much helpful if there are many columns. 

Thanks.
