### ISSUE TITLE
Returning null value for a String type using 1.5

### ISSUE THREAD

**Issue by phatthinh123** [ozlerhakan/poiji#11]
Backthen when it's 1.4 it will return empty in case just string alone
After new update it's return null if the cell is empty 
I mean when the column present is empty it will return me null value although it's type String 
Thank you

**Comment by ozlerhakan** [comment]
yes, if a cell is empty for a `xlsx` file, that corresponding field will be null if it is `String`.  Do you want the old behavior for 1.5?
