### ISSUE TITLE
v2.2.0 Regression: @ExcelRow handling has changed for empty rows

### ISSUE THREAD

**Issue by Brutus5000** [ozlerhakan/poiji#111]
## Sample data:
Imagine you have the following excel sheet:

| First Header  | Second Header |
| ------------- | ------------- |
| _null_ | _null_ |
| First Row  | Content Cell  |
| Second Row  | Content Cell  |

## Previous behavior
Up to version 1.22.0 the RowIndex would have been:
1: unused (for null row)
2: for First Row
3: for Second Row

## New behavior
With 2.2.0 this behavior has changed! The null row is no longer taken into consideration. The indices are now referring to the following:
1: First Row
2: Second Row

I prefer the old behavior, as this is the only way to tell the user in which line we found errors.

**Comment by ozlerhakan** [comment]
> as this is the only way to tell the user in which line we found errors.

are you sure about this?

**Comment by ozlerhakan** [comment]
but it make sense the null rows are not counted

**Comment by Brutus5000** [comment]
So I am running a lot of validations on each row and we are talking about hundreds, sometimes thousands of rows.
In case of an error I return the line number which exactly matches the shown row index of Excel, so he can just go there and fix the error .
And there may be reasons that the user has empty lines in there. So if this happens the reference line of my error message no longer matches the "real" line number.

Skipping empty lines makes sense if you treat the rows as an index that you want to address by row number. But from an excel user perspective it does not make sense to skip any lines. 

Maybe we can have both indices?

**Comment by breucode** [comment]
As the annotation is called @ExcelRow, this behavior is very confusing. I would also suggest, that there is a separate annotation with a different naming for counting non-null rows.

**Comment by breucode** [comment]
I'm currently working on this.

**Comment by ozlerhakan** [comment]
thank you @breucode

**Comment by breucode** [comment]
This was actually a regression, like originally expected. If you revert the the PoijiHandler class to the version of 2.2.0, you see, that one of the two new unit tests fails.
