### ISSUE TITLE
Feature Request: Serialize back to Excel

### ISSUE THREAD

**Issue by bitbythecron** [ozlerhakan/poiji#112]
I recently had a project where I needed to deserialize an Excel spreadsheet into a list of POJOs, process that list, and then write that list _back_ into another Excel file.

I was **very** impressed with this library's capabilities and use of annotation processing, etc. However I had to pass on it because it didn't offer serialization & write from the list of POJOs --> Excel.

Is this a feature that this community is interested in? If so I'd be happy to provide a PR for it!

**Comment by ozlerhakan** [comment]
thank you for using poiji @bitbythecron , you're free to make this feature enable for poiji :)

**Comment by ozlerhakan** [comment]
did you start doing @bitbythecron ?

**Comment by ozlerhakan** [comment]
feel free to comment here when you start it @bitbythecron
