### ISSUE TITLE
Is the default DateFormatter pattern correct?

### ISSUE THREAD

**Issue by Brutus5000** [ozlerhakan/poiji#118]
I am working on German locale so it might not be a real issue, but parsing dates into java.time.LocalDate fails because of a mismatch in the default DateFormatter pattern.

The default DateFormatter pattern in poiji is `dd/M/yyyy`.
However the matching pattern that I get from poi would be `d/M/yy` (e.g. 1/1/20).

Can somebody confirm that the default also does not match on english locale?
I have fixed this with setting a custom DateFormatter (as mentioned in #48). Just want to make sure, that the default is correct.

**Comment by ozlerhakan** [comment]
Hi @Brutus5000 , I think we can close this issue. If we have more comment on it, we can open the question again
