### ISSUE TITLE
What about column mapping?

### ISSUE THREAD

**Issue by RobertoPelonara** [ozlerhakan/poiji#123]
Poiji is a great library for mapping object row based, but what about column mapping? 

Maybe I simply missed the way of do it, or maybe it's not possible at all

EDIT:
![image](https://user-images.githubusercontent.com/13091425/71971563-2715f180-320b-11ea-8f5d-dd5a72fc6e8d.png)
 
I have this kind of structure and I'd like to map each column in a seperate object taking the first column as "header"

**Comment by ozlerhakan** [comment]
good idea @RobertoPelonara , we can implement this feature. If you want you can take it as well

**Comment by ozlerhakan** [comment]
if any request is needed we can start implementing it so currently it's a nice-to-have
