### ISSUE TITLE
Case insensitive column names option

### ISSUE THREAD

**Issue by vaa25-digis** [ozlerhakan/poiji#124]
Could you add support of case insensitive column names option please?

 **Example**:

Option:

```PoijiOptions.PoijiOptionsBuilder.settings().caseInsensitive(true);```

Excel table:

| ID     | NamE   |
|--------|--------|
| 123923 | Joe    |
| 123123 | Sophie |
| 135923 | Paul   |

Class:

```
public class Employee {

    @ExcelCellName("id")
    private long employeeId;

    @ExcelCellName("name")
    private String name;

    @Override
    public String toString() {
        return "Employee{" +
                "employeeId=" + employeeId +
                ", name='" + name + '\'' +
                '}';
    }
}
```

Result:

```Employee{employeeId=123923, name='Joe'}```

**Comment by ozlerhakan** [comment]
Hey @vaa25-digis , 

sounds great! we can implement it.  you can implement it as well

**Comment by vaa25** [comment]
@ozlerhakan I have cloned this repository and implemented feature in new branch. How to make pull request? I can not push new branch.

**Comment by ozlerhakan** [comment]
Hi @vaa25-digis , you can create a pull request on the 2.5.0 branch (https://github.com/ozlerhakan/poiji/tree/2.5.0)

**Comment by ozlerhakan** [comment]
now we're able to do this 🎉
