### ISSUE TITLE
Unblock multithreaded calls

### ISSUE THREAD

**Issue by vaa25** [ozlerhakan/poiji#128]
Current implementation has `synchronous` modifier on every _fromExcel_ method in Poiji class. If we parse huge files with heavy custom Consumers from different threads every file processing could take much time and other threads will be blocked.

Poi [says](https://poi.apache.org/help/faq.html): 'Handling different document-objects in different threads will work.'

And Poiji uses new Unmarshaller for every _fromExcel_ call. Has Poiji any reasons to synchronize every _fromExcel_ method?

**Comment by ozlerhakan** [comment]
so we don't need `synchronous ` am i right? @vaa25

**Comment by ozlerhakan** [comment]
so we don't need `synchronous ` am i right? @vaa25

**Comment by vaa25** [comment]
@ozlerhakan we need to write tests to be sure

**Comment by vaa25** [comment]
@vaa25 tests have been added in #129 . Thread-safe reading confirmed.

**Comment by ozlerhakan** [comment]
Hi @vaa25 , why you close the pr?

**Comment by vaa25** [comment]
Hi @ozlerhakan , you have no time to maintain project, so I have published my improvements in my repository

**Comment by ozlerhakan** [comment]
We can at least look at this task if you are willing , otherwise that's all fine.
