### ISSUE TITLE
Add multiple column names support

### ISSUE THREAD

**Issue by vaa25** [ozlerhakan/poiji#130]
Could you add support of multiple column names please?

 **Example**:

Class:

```
public class Employee {

    @ExcelCellName(name="id,identifier")
    private long employeeId;

    @ExcelCellName(name="name,title,nick", delimeter=",")
    private String name;

    @Override
    public String toString() {
        return "Employee{" +
                "employeeId=" + employeeId +
                ", name='" + name + '\'' +
                '}';
    }

}
```
_Writing:_

Result excel table:

| id,identifier    | name   |
|--------|--------|
| 123923 | Joe    |
| 123123 | Sophie |
| 135923 | Paul   |

_Reading:_

Source excel table:

| id,identifier    | nick   |
|--------|--------|
| 123923 | Joe    |
| 123123 | Sophie |
| 135923 | Paul   |

Result:

Employee{employeeId=123923, name='Joe'}

**Comment by ozlerhakan** [comment]
Hi @vaa25 , this gives us performance issues while searching the name in the available names.

**Comment by vaa25** [comment]
@ozlerhakan why do you think so? all names are stored in the map. In example case it would be
{
"id,identifier": 0,
"name": 1,
"title": 1,
"nick": 1
}
So mapping from excel takes O(1) - same as without this feature.

**Comment by vaa25** [comment]
@ozlerhakan feature is implemented. No any performance issues found nor reading nor writing.
