### ISSUE TITLE
File handle is left open on XLS

### ISSUE THREAD

**Issue by bsungur** [ozlerhakan/poiji#134]
When using `fromExcel ` with an XLS `File` the file is left open after Poiji has returned the list of objects.

In my use case, I was not able to save changes to the Excel workbook while my application was running, after Poiji accessed the file.

**Comment by bsungur** [comment]
According to POI Javadoc https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/WorkbookFactory.html#create-java.io.File-java.lang.String-boolean-

> Note that in order to properly release resources the Workbook should be closed after use.

**Comment by ozlerhakan** [comment]
thanks @bsungur , we'll add this case for 2.6.0.
