### ISSUE TITLE
Merged cells: null value for all cells except first one

### ISSUE THREAD

**Issue by cronosnn** [ozlerhakan/poiji#139]
Hi
I've receive null value fol all cells except first one in case that cells are merged.
Do you have option to configure it or?

Thanks in advice.

**Comment by ozlerhakan** [comment]
Hi @cronosnn , 

Could you  please elaborate more about the case you have encountered with examples?

**Comment by cronosnn** [comment]
Hi

Hi I have an excel:

------------------------
| Scenario | Test Case | 
------------------------
|                | tc1           |
|  Scen1    | ---------- |
|                | tc2           |
------------------------

And use class
public class MainSheetRecord {
    public static final String SCENARIO = "Scenario";
    public static final String TESTCASE= "Test Case";
    @ExcelCellName(SCENARIO)
    private String scenario;
    @ExcelCellName(TESTCASE)
    private String testcase;
}

after parsing I have:
MainSheetRecord[0] : 
    scenario="Scen1",
    testcase="tc1"
and
MainSheetRecord[1] : 
    scenario=null,
    testcase="tc2"

How I can have (maybe you know example using CustomCasting)?
MainSheetRecord[1] : 
    scenario="Scen1",
    testcase="tc2",

**Comment by ozlerhakan** [comment]
Hi @cronosnn ,

You can use CustomCasting. If the value for the field is of type `String`, you can set a default value (in your case is `"Scen1"`)
