### ISSUE TITLE
No record in Map in case ExcelUnknownCells and empty value

### ISSUE THREAD

**Issue by cronosnn** [ozlerhakan/poiji#140]
Hi I have a excel:

-----------------------------------------------------------------
| Scenario | Description | Column 1 | Column 2 | Column N |
-----------------------------------------------------------------
| Scen1     | Descrip1      | col1          | col2         | colN          |
-----------------------------------------------------------------
| Scen2     | Descrip2      | col1.2       |                 | colZ          |
-----------------------------------------------------------------

And use slass
public class MainSheetRecord {
    public static final String SCENARIO = "Scenario";
    public static final String DESCRIPTION = "Description";
    @ExcelCellName(SCENARIO)
    private String scenario;
    @ExcelCellName(DESCRIPTION)
    private String description;
    @ExcelUnknownCells
    private Map<String, String> otherCells;
}

after parsing I have:
MainSheetRecord[0] : 
    scenario="Scen1",
    description="Descrip1",
    otherCells={
        "Column 1" -> "col1",
        "Column 2" -> "col2",
        "Column N" -> "colN"
    }
and
MainSheetRecord[1] : 
    scenario="Scen2",
    description="Descrip2",
    otherCells={
        "Column 1" -> "colN",
        "Column N" -> "colZ"
    }

How I can have (maybe you know example using CustomCasting)?
MainSheetRecord[1] : 
    scenario="Scen2",
    description="Descrip2",
    otherCells={
        "Column 1" -> "colN",
        "Column 2" -> null,
        "Column N" -> "colZ"
    }
or better "Column 2" -> "" if value in column is absent

**Comment by ozlerhakan** [comment]
Hi @cronosnn ,

Since MainSheetRecord[1] doesn't have `Column 2`, you can check the otherCells using `containsKey` whether the column name (key) exists ot not.

**Comment by cronosnn** [comment]
Hi @ozlerhakan,

Yes
```MainSheetRecord[0].otherCells.containsKey("Column 2"); //true
MainSheetRecord[1].otherCells.containsKey("Column 2"); //false```

but I expected
```MainSheetRecord[0].otherCells.containsKey("Column 2"); //true
MainSheetRecord[1].otherCells.containsKey("Column 2"); //true
MainSheetRecord[0].otherCells.get("Column 2");  //col2
MainSheetRecord[1].otherCells.get("Column 2");  //null or empty```
