### ISSUE TITLE
How to use LinkedHashMap in case of ExcelUnknownCells

### ISSUE THREAD

**Issue by cronosnn** [ozlerhakan/poiji#141]
Hi, I have following:
```
public class MainSheetRecord {
    @ExcelCellName("Scenario")
    private String scenario;
    @ExcelUnknownCells
    private LinkedHashMap<String, String> otherCells;
}
```
How to use LinkedHashMap for otherCells?
if I try 
`private LinkedHashMap<String, String> otherCells;`
then I see exception :
`java.lang.IllegalArgumentException: Can not set java.util.LinkedHashMap field MainSheetRecord.otherCells to java.util.HashMap`

**Comment by ozlerhakan** [comment]
Hi @cronosnn , we cannot cast superclass (`HashMap`) to subclass (`LinkedHashMap`) . You should use `Map` or `HashMap` with `@ExcelUnknownCells`

**Comment by cronosnn** [comment]
How can I receive `otherCells` in order as I see it in Excel file?
