### ISSUE TITLE
Get all columns name of @ExcelUnknownCells

### ISSUE THREAD

**Issue by cronosnn** [ozlerhakan/poiji#142]
Hello,

I have Excel file with 6000+ records.
I know name only 2 first columns and I know that all cells in those columns are non empty.
But for all other columns I don't know count of them and names. Also cells in those columns can be empty.
my classes:
```
public class Sheet {
  private List<SheetRecord> records;
}
public class SheetRecord {
    @ExcelCellName("Column1")
    private String col1;
    @ExcelCellName("Column2")
    private String col2;
    @ExcelUnknownCells
    private HashMap<String, String> otherCells;
}
```
So, after parsing excel I have List<SheetRecord> with size 6000+
How can I know names of all columns for @ExcelUnknownCells?
maybe something like:
```
public class Sheet {
  @ExcelUnknownCellsAllKeys
  private List<String> excelUnknownCellsAllKeys;
  private List<SheetRecord> records;
}
```

**Comment by cronosnn** [comment]
One more question, how can I get @ExcelUnknownCells in the same order how I see it in Excel file?

**Comment by ozlerhakan** [comment]
Hi @cronosnn ,

Could this example solve your problem https://github.com/ozlerhakan/poiji#example-8 ?

> One more question, how can I get @ExcelUnknownCells in the same order how I see it in Excel file?
This is not available with Poiji. We need to implement it with `LinkedHashMap` in order to do so.

**Comment by vaa25** [comment]
@cronosnn 
> How can I know names of all columns for @ExcelUnknownCells?

`otherCells.keySet()` ?

>One more question, how can I get @ExcelUnknownCells in the same order how I see it in Excel file?

```
@ExcelUnknownCells
private Map<String, String> otherCells = new LinkedHashMap<>();
```

**Comment by cronosnn** [comment]
> @cronosnn
> 
> > One more question, how can I get @ExcelUnknownCells in the same order how I see it in Excel file?
> 
> ```
> @ExcelUnknownCells
> private Map<String, String> otherCells = new LinkedHashMap<>();
> ```
> 
> P.S. verified on https://github.com/vaa25/poiji/tree/130-multiple-column-names

Thank you, I'm going to check till the end of this week
