### ISSUE TITLE
Unable to identify error cell while using default casting

### ISSUE THREAD

**Issue by chinmay1994** [ozlerhakan/poiji#146]
Hi,
I want to find out the location of the cell with a type mismatch. When I set `errorLoggingEnabled` to true in the `DefaultCasting()` constructor and pass it to the `withCasting` method of PoijiOptions, I encounter the following issues:
1. The row and column are always populated with -1. I checked in the `PoijiHandler.java` file, the `casting.castValue()` method is called without the row and column arguments because of which the location of error cell will never be found.
2. When `errorLoggingEnabled` is set to true, errors for each cell are added twice to the `errors` list in the DefaultCasting. 

Suggested fix for point 1
There is an `internalRow` field in the `PoijiHandler` class, which I believe points to the current row being processed. The `column` argument is passed to all functions from which the `casting.castValue()` method is being called. Thus, we can pass `internalRow` and `column` arguments to the `castValue` method to populate the row and column number in `DefaultCastingError`.

**Comment by ozlerhakan** [comment]
Hi @chinmay1994 ,

> The row and column are always populated with -1. I checked in the PoijiHandler.java file, the casting.castValue() method is called without the row and column arguments because of which the location of error cell will never be found.

You're right, we'll fix this.

> When errorLoggingEnabled is set to true, errors for each cell are added twice to the errors list in the DefaultCasting

how can I reproduce this issue?

**Comment by chinmay1994** [comment]
Hi @ozlerhakan ,

Appreciate the quick reply.
> how can I reproduce this issue?

To reproduce this issue, you can create a pojo with an Integer field and try to set a String value to it via the excel file. You'll see that that the NumberFormatException is added twice to the `errors` list in the `DefaultCasting` implementation.

I debugged this issue, my findings are as follows: 
When the `containsKey` method is checked in the [columnToSuperClassField](https://github.com/ozlerhakan/poiji/blob/12283d9c006960bdef2e8bb84e076dc556999225/src/main/java/com/poiji/bind/mapping/PoijiHandler.java#L146) map, the `setValue(Field field, int column, String content, Object ins)` is called if the key is absent. However, this map is populated only when the `ExcelCellRange` annotation is applied. If this annotation is not present and only `ExcelCell` or `ExcelCellName` annotations are present, the `setValue(Field field, int column, String content, Object ins)` method is already called in [this](https://github.com/ozlerhakan/poiji/blob/12283d9c006960bdef2e8bb84e076dc556999225/src/main/java/com/poiji/bind/mapping/PoijiHandler.java#L110) line. 

To fix this, if the `columnToFieldMap` contains the key but the `columnToSuperClassField` doesn't, we can return `false` instead of returning the result of the `setValue` method.

I have fixed both these issues locally, [this](https://github.com/ozlerhakan/poiji/pull/147) is the PR for the same.

**Comment by ozlerhakan** [comment]
now released with 2.6.0 thanks @chinmay1994
