### ISSUE TITLE
Casting with different datatypes

### ISSUE THREAD

**Issue by deivanayagis** [ozlerhakan/poiji#149]
Hi Can you help me with different casting for different datatypes?

1. Eclipse is throwing error if I am not adding either of the following methods to my cast class
`package Reports.ReportsAutomationProject;

import com.poiji.config.Casting;
import com.poiji.option.PoijiOptions;

public class ReportCast implements Casting {

	@Override
	public Object castValue(Class<?> fieldType, String value,
			PoijiOptions options) {
		//System.out.println("Casting method:"+value);
		if(value == null || value.isEmpty()){
			//System.out.println("being casted");
			return "0.0";
		}
		//System.out.println("not being casted");
		return value;
	}

	@Override
	public Object castValue(Class<?> fieldType, String value, int row,
			int column, PoijiOptions options) {
		System.out.println("Casting method:"+value);
		System.out.println("FieldType:"+fieldType);
				if(value == null || value.isEmpty()){
					System.out.println("being casted");
					return "0.0";
				}
				//System.out.println("not being casted");
				return value;
	}
}
`
But is this correct why do we need 2 different methods? or when will int row, int column be used?

2. I am looking for automating the reading of a report. So when I see empty values in few columns I would like to convert them to "0.0". I want the columns which are of datatype double alone to be casted. How to handle this?

Your help is much appreciated!

**Comment by ozlerhakan** [comment]
Hi @deivanayagis ,

1. could you please use the latest version of poiji which is 2.6.0, we not have one castValue method. 
2. you can give a default value for each field e.g. https://raw.githubusercontent.com/ozlerhakan/poiji/master/src/test/java/com/poiji/deserialize/model/byid/Employee.java for the name field.

**Comment by ozlerhakan** [comment]
feel free to leave a comment if you have a problem

**Comment by deivanayagis** [comment]
Thank you. It worked.
