### ISSUE TITLE
Dates with an incomplete format in .xlsx file are not being parsed.

### ISSUE THREAD

**Issue by evaldeslacasa** [ozlerhakan/poiji#150]
Hello @ozlerhakan.

Thanks a lot for Poiji, it's been of great use so far!

Now, I ran into an issue while using it (although I'm not sure if it's really an issue, or just the way .xlsx stores the information). I upgraded to the latest version (2.6.0) to see if maybe the problem/issue went away, but I'm still experiencing it.

Here is the thing: if you see the .xlsx file I attached, it has three columns: date1, date2 and date3. 

[dates-not-empty.xlsx](https://github.com/ozlerhakan/poiji/files/4529893/dates-not-empty.xlsx)

The three columns seem to have empty values...but if you double click on any of the cells in Excel, you should see the full date displaying (with day, month and year not empty).

The issue is that whenever I try to parse the file using the initial cell format (which just displays  values in the format:  `hh:mm.s`)...Poiji ignores the day, month and year. I tried this with both types, `String` and `Date` for `@ExcelCellName(...)`, but in both of them it doesn't get the full date.

Now, in Excel, if you double click on any on the cells, the full date should show up (for example, for the date3 value would be: `09/11/2015 00:00`). After that, if I hit "Save" in Excel, and go on to parse it like that, I will get the date3 value parsed correctly. 

I was wondering if this an issue within Poiji, or perhaps something outside of it? I've been developing in Java for a few years, but I'm not sure if I could be of help to look into it.

Anyway, I thought it was a good idea to reach out just in case.

Thank you for your work and time!

**Comment by ozlerhakan** [comment]
Hi @evaldeslacasa ,

Thanks for using poiji and find it useful :)

About your case, I looked at the problem. Here is the default XFS format for the style apache poi uses internally when we directly use the excel file with poiji:

```
<xml-fragment numFmtId="47" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>
```

And after doing these steps:

> Now, in Excel, if you double click on any on the cells, the full date should show up (for example, for the date3 value would be: 09/11/2015 00:00). After that, if I hit "Save" in Excel, and go on to parse it like that, I will get the date3 value parsed correctly.

```
<xml-fragment numFmtId="22" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" xmlns:x16r2="http://schemas.microsoft.com/office/spreadsheetml/2015/02/main" xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision"/>
```
Here you see that the `numFmtId` value for both is changed 22 and 47 respectively. These are the indexes of the builtin formats Apache Poiji uses internally. Thus, we need to override the default format of these indexes in order to display the cell value properly. 

We can add another option to make this possible with 2.7.0. Using this option, users are able to override default formats of a specific index. Here I can achieve this on my local and give the correct date and time values : 

```
DateExcelColumn {
date1='12/31/2020 12.00 AM', 
date2='11/09/2015 12.00 AM', 
date3='11/09/2015 12.00 AM'
}
```

**Comment by evaldeslacasa** [comment]
Hello @ozlerhakan,

Thanks for the detailed reply and the insights! My apologies for not being able to reply earlier. I'm in the middle of a busy project and can't attend much outside of it, but I'll try to sqeeze time along.

Correct me if I'm wrong in my knowledge of the issue and possible solution:

- Apache POI uses indexes for each date format, and the index (`numFmtId`) is fixed by the format of the date cell in the Excel file.
- Problem: a format that has missing time values (like yyyy-MM-dd) don't get read.
- Solution: let users choose with an option what kind of format (under the hood, the `numFmtId`) will be the default date format to read.

My question about the solution is:

- Would the option make Poiji capable of reading **any** kind of date format without missing time values (as long as the users specify the date format with the option).

If that is the case, it would be an awesome feature for the library. I am not sure if I am capable of contributing into it myself, but if you think I could be of help with some of code, please let me know.

Thanks again, regards.

**Comment by ozlerhakan** [comment]
Hi @evaldeslacasa ,

You can able to override the default format of a specific index using 2.7.0 :)
Please look at the feature 10 and feature 11 sections on README

thank you for your help! leave a comment if you have any questions.

**Comment by evaldeslacasa** [comment]
Thanks to you @ozlerhakan! I'll reach out when I use the option in the newer version.

Best regards.
