### ISSUE TITLE
Add reading fields from custom properties (metadata)

### ISSUE THREAD

**Issue by breucode** [ozlerhakan/poiji#151]
Currently, it is not possible to read meta data from an excel file (example here: https://stackoverflow.com/questions/43796819/how-to-write-metadata-into-excel-workbooks-using-apache-poi-in-java).

This would be very helpful for one of our use cases.

Would it be ok for you, if we provided a PR for this feature @ozlerhakan ?

I would propose a separate option for the PoijiOptions object and then get the data from the excel meta data. The semantics of annotations and everything should be the same.

**Comment by ozlerhakan** [comment]
Hi @breucode ,

Feel free to make a PR, it's all fine to contribute the project.

**Comment by ozlerhakan** [comment]
thank you @breucode , merged the code! you can use 2.8.0 now for the property feature

**Comment by breucode** [comment]
Great, thanks!
