### ISSUE TITLE
Format-independent date parsing

### ISSUE THREAD

**Issue by grolex18** [ozlerhakan/poiji#155]
In Excel format date is stored as simple Numeric value.
Is there a way to read it as a Date field regardless of the format/locale?
Looks like under the covers poiji extracts String value from Cell first and then parses it to java Date, if required. And Casting/formatters customizations work on top of String values anyway.

But what if I can't stick to some specific format/locale and need consistent way of parsing Date (that is technically possible from numeric value). Is it possible with poiji configuration, or should I render it as Integer field and then convert it to Date manually?

**Comment by ozlerhakan** [comment]
Hi @grolex18 ,

could you please look at the feature 10 and feature 11 on README. you could debug and see the default cell format of each cell and you can event override formats with an user specific parsing format. Moreover, you can look at the text cases for `datePattern` and `dateTimeFormatter` on poijioptions.

**Comment by grolex18** [comment]
Hi @ozlerhakan,
Thanks for your quick reply!
Looks like feature 10 is more about debugging and 11 suggests adding all possible pairs of format number and pattern?
Is it the only option to extract the date in a consistent way?
It might be hard and unreliable to hard-code all possible locales/cases with this approach.

It's quite simple and unambiguous with plain POI, though:
org.apache.poi.ss.usermodel.Cell.getDateCellValue()
or
DateUtil.getJavaDate(cell.getNumericCellValue())

**Comment by ozlerhakan** [comment]
If I understand you clearly, once you get the string value of a cell, you can convert it to date as well in poiji e.g. https://github.com/ozlerhakan/poiji/blob/81f0ab2fc92705a2bfcfeb9fc38cccb7d58ccb14/src/main/java/com/poiji/config/DefaultCasting.java#L228.

Do I miss something?

**Comment by grolex18** [comment]
The concept of Casting works on top of already formatted string cell representation that makes its further decoding into java Date dependant on cell format/style/localization. It means you need to have all format/style/localization info in Casting.castValue to revert it back correctly. E.g. you don't exactly know if "2/1/20" means "2 Jan 2020" or "1 Feb 20". Even though in the source it was defined unambiguously.

One option would be letting Casting process Cell-s directly (instead of string-s), another is to have some config option to transform dates into their numerical representation in a string form before passing to Casting ("String.valueOf(cell.getNumericCellValue()" instead of "dataFormatter.formatCellValue(cell)")
So Casting can parse this String into double and then transform it into Date/DateTime/etc.
Maybe some other ways fit better into Poiji, I've just started looking into it. But for now, I don't see a robust way to decode Date cells that works for all cell formats.

**Comment by grolex18** [comment]
For example, now I have these formats in the some document:
`<numFmt numFmtId="166" formatCode="M/D/YYYY"/>`
`<numFmt numFmtId="169" formatCode="DD/MM/YYYY"/>`

They were added based on changing cell format locales.
numFmtId-s are purely custom for this document, am I right?
So next time ids could be different and I'd have to somehow reflect them in my code every time.

**Comment by ozlerhakan** [comment]
a user-defined custom format starts at 164 see: https://github.com/apache/poi/blob/cafe7639c2168a14b72bef738150cbcfa91e56ca/src/ooxml/java/org/apache/poi/xssf/model/StylesTable.java#L79

and there can be up to 250 formats in an excel file:

https://github.com/apache/poi/blob/cafe7639c2168a14b72bef738150cbcfa91e56ca/src/ooxml/java/org/apache/poi/xssf/model/StylesTable.java#L86

> numFmtId-s are purely custom for this document, am I right?
I guess so

**Comment by evaldeslacasa** [comment]
Hello @ozlerhakan!

You'll remember me from Issue #150. I hadn't been able to play with the latest features 10 and 11 until now, so I didn't reached out.

I write here because I can relate to @grolex18 comment about overriding date formats.

When I do this, I'm telling Poiji to override a specific numFtId with my format...but Excel files could provide cells in different formats, so it would be painful to go one by one overriding them all.

```
            PoijiNumberFormat numberFormat = new PoijiNumberFormat();
            numberFormat.putNumberFormat((short) 47, "mm/dd/yyyy");
```

In my opinion, it would be more convenient for developers to be abstracted of having to find out about the id numbers first. Doing something like:

```
            PoijiDateFormat dateFormat = new PoijiDateFormat();
            dateFormat .putDateFormat("mm/dd/yyyy");
```

so that regardless of the date format in the Excel file, the dates would all be parsed using a single date format provided.

Thanks again!

**Comment by grolex18** [comment]
Open office (and Excel, probably also) can add custom formats for dates with some random ids, so it's not feasible to cover this case having only string representation and formatId-based configs at all.
It looks like it's a big deal in the framework itself.
Thanks for your help anyway!
