### ISSUE TITLE
data check support

### ISSUE THREAD

**Issue by westontan** [ozlerhakan/poiji#158]
Is it possible to support "data check" feature?
(1) bean validation
(2) unique constraint - unique value in a column

Thanks!

**Comment by westontan** [comment]
![image](https://user-images.githubusercontent.com/3642707/83489880-b6d17a80-a4e1-11ea-8c83-7cd8f45a24c6.png)

**Comment by ozlerhakan** [comment]
does https://github.com/ozlerhakan/poiji#feature-9 solve your need @westontan ?

**Comment by westontan** [comment]
Totally not
Take the picture I uploaded as an example:
There are four properties annotated with @NotBlank, which means the value of them are not allowed to leave blank.
Assume now we have an excel file containing a row that violate @NotBlank constraint.
With bean validation feature, when Poiji.fromExcel is invoked, a ConstraintViolationException would be thrown.

**Comment by westontan** [comment]
unique constraint means a unique value of a column in each row must be ensured.

**Comment by ozlerhakan** [comment]
Sorry I pointed out totally different feature. I see now, we can take a look at it. Also if you want to make it possible, PR is always welcome

**Comment by Brutus5000** [comment]
I would not recommend to put this into Poiji due to separation of concerns. You can apply any validation rules onto the beans and validate it after deserializing with Poiji (e.g. in a project we use Spring validation).

**Comment by westontan** [comment]
The reason why Poiji need to add this as a built-in feature is that javax.validation.ConstraintViolation.getPropertyPath() would return the bean property name instead of the value of @ExcelCellName

**Comment by gvh1234** [comment]
If you use Hibernate Validator you can put a message in the constraint annotation for each field. You then use a great validation system and not compromise this code.

**Comment by ozlerhakan** [comment]
seems like it's not a obligatory and necessary approach for poiji, feel free to talk more about on this topic. we can look at it later again
