### ISSUE TITLE
Unable to correctly convert negative numbers with parentheses

### ISSUE THREAD

**Issue by superigno** [ozlerhakan/poiji#161]
I tried to convert a cell with a negative number in parentheses. ie: (1234) instead of -1234.

It returns 0 when I use a BigDecimal:
```
@ExcelCell(1)
private BigDecimal amount;
```
Returns: 0

----

So I tried a workaround by using String as type:
```
@ExcelCell(1)
private String amount;
```
Which basically returns (1234), but then I have to remove the parentheses and convert this to a negative BigDecimal, which I find a bit of a hassle.

Am I missing something?

**Comment by ozlerhakan** [comment]
Hi @superigno , could you share an excel file we can look?

**Comment by superigno** [comment]
Please see: [Test.zip](https://github.com/ozlerhakan/poiji/files/4778127/Test.zip)

![image](https://user-images.githubusercontent.com/4880653/84620772-3157bc80-af1c-11ea-8bbd-5c63fa9d67e7.png)

```
public class TestInfo {
   @ExcelRow                    
   private int rowIndex;
   @ExcelCell(0)
   private String desc;
   @ExcelCell(1)
   private BigDecimal amount;

   public String getDesc() {
      return desc;
   }
   public BigDecimal getAmount() {
      return amount;
   }	
}
```
```
@Test	
void test() {
   List<TestInfo> list = Poiji.fromExcel(new File("Test.xls"), TestInfo.class);
   list.stream().forEach(i -> System.out.println(i.getAmount()));
}
```

Output:
123.00
25.00
0
0

**Comment by ozlerhakan** [comment]
Hey @superigno ,

After debugging I have found that we have the value like "(50)" but in the default casting procedure, we cannot cast string as "(50)" to bigdecimal.  There are 2 options here, 

1. you can enable logging using `new DefaultCasting(true)` in the PoijiOptions and see all errors during mapping using `getErrors() of the casting class`. 
2. You can implement your own custom casting class to cast value like "(200)"
3. We need to way to parse such data using the default poiji casting class

**Comment by ozlerhakan** [comment]
In addition to my previous comment, you can use poiji 3.0.0 to parse the number cells using **Feature 13** on README.adoc :)
