### ISSUE TITLE
Can I use poiji to write data into Excel? 

### ISSUE THREAD

**Issue by acyuta1** [ozlerhakan/poiji#162]
Thankyou so much for this amazing library. Just wanted to ask, can this be used to write object data into a file? (Xlsx or csv)?

**Comment by ozlerhakan** [comment]
Hey @acyuta1 , 

Thank you so much :) poiji does not support "toExcel" , feel free to make this possible via PR if you want it

**Comment by vaa25** [comment]
@acyuta1 maybe [this one](https://mvnrepository.com/artifact/io.github.vaa25/poiji2) can help you
