### ISSUE TITLE
PoijiHandler.cell()  is not ignoring earlier header lines when using PoijiOptions .headerStart(1)

### ISSUE THREAD

**Issue by gvh1234** [ozlerhakan/poiji#163]
[As discussed elsewhere](https://github.com/ozlerhakan/poiji/pull/115#issuecomment-657495569), if you set .headerStart(1) in PoijiOptions I would expect everything on the top line to be ignored and the headers started on the second line.
However I think that PoijiHandler.cell() is pulling in line zero into the headers because of the _if_ statement on line 205.

This is an example of the sheet I have to parse, all of the Options would be parsed into a Map<String, String> using @ExcelUnknownCells

![image](https://user-images.githubusercontent.com/6451320/87311720-8553c200-c517-11ea-903a-93298ee7c1d6.png)

**Comment by ozlerhakan** [comment]
Hi @gvh1234 ,

Thank you for bringing this up. feel free to make a PR for that change :)

**Comment by ozlerhakan** [comment]
the fix will be ready on 3.0.0

**Comment by gvh1234** [comment]
Sorry, ran out of time this week and am on holiday next week

thanks for taking a look

**Comment by ozlerhakan** [comment]
fix is ready with 3.0.0
