### ISSUE TITLE
Excel file without headers, skipping first line

### ISSUE THREAD

**Issue by fernando1983github** [ozlerhakan/poiji#164]
We are trying to use the library on an excel without headers(We set a template for download to show the way its meant to be used, but apparently thats not what they have in mind), but we saw in the code, that no matter what, the first row is always ignored because of the hardcoded `+ 1`, there´s no way we can set `skip` or `headerStart` as negative cause an exception is thrown. Is there an option we hadn't see to read an excel without headers?
```java
        public static PoijiOptionsBuilder settings(int skip) {
            if (skip < 0) {
                throw new PoijiException("Skip index must be greater than or equal to 0");
            }
            return new PoijiOptionsBuilder(skip);
        }
```
```java
        public PoijiOptionsBuilder headerStart(int headerStart) {
            if (headerStart < 0) {
                throw new PoijiException("Header index must be greater than or equal to 0");
            }
            this.headerStart = headerStart;
            return this;
        }
```
```java
        public PoijiOptions build() {
            return new PoijiOptions()
                    .setSkip(skip + headerStart + 1)
                    .setPassword(password)
                    .setPreferNullOverDefault(preferNullOverDefault)
                    .setDatePattern(datePattern)
                    .setDateFormatter(dateFormatter)
                    .setDateTimeFormatter(dateTimeFormatter)
                    .setSheetIndex(sheetIndex)
                    .setSheetName(sheetName)
                    .setIgnoreHiddenSheets(ignoreHiddenSheets)
                    .setTrimCellValue(trimCellValue)
                    .setDateRegex(dateRegex)
                    .setDateTimeRegex(dateTimeRegex)
                    .setDateLenient(dateLenient)
                    .setHeaderStart(headerStart)
                    .setCasting(casting)
                    .setLimit(limit)
                    .setPoijiLogCellFormat(cellFormat)
                    .setPoijiNumberFormat(numberFormat)
                    .setCaseInsensitive(caseInsensitive)
                    .setNamedHeaderMandatory(namedHeaderMandatory);
        }
```

**Comment by ozlerhakan** [comment]
Hi @fernando1983github ,

Normally, every excel file must contain a header row, so we need to change this behavior to make it possible

**Comment by ozlerhakan** [comment]
the fix will be ready on 3.0.0

**Comment by fernando1983github** [comment]
Hi @ozlerhakan, wasn't able to respond. That's great news, thanks for the immediate response, looking forward to it.

**Comment by ozlerhakan** [comment]
fix is ready with 3.0.0

**Comment by sriram0626** [comment]
[testExcel.xlsx](https://github.com/ozlerhakan/poiji/files/8668298/testExcel.xlsx)
Hi @ozlerhakan I have an excel like the one i attached. When i read it using POIJI.FromExcel, i am not getting the values to the object. Could you please help me to understand what is wrong here or what i need to do here to read the values ?

**Comment by ozlerhakan** [comment]
Hi @sriram0626 ,

You need you use `PoijiOptions` to refer that your header starts at line 1:

```
PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings().headerStart(1).build();
Poiji.fromExcel(new File("src/test/resources/testExcel.xlsx"), TestSampleInfo.class, options);
```

**Comment by sriram0626** [comment]
Thanks @ozlerhakan . Yeah i have tried this and it works.

**Comment by vansh-bhatia** [comment]
> the fix will be ready on 3.0.0

Hi @ozlerhakan, 
How do we get the headers also as part of the response? Our usecase is that we want the headers as well.
```
if (skip <= 0) {
                throw new PoijiException("Poiji already skips the header. Skip index must be greater than 1");
            }
return new PoijiOptionsBuilder(skip + 1);
```
 Since skip can't be negative, is there a fix?
Thanks

**Comment by ozlerhakan** [comment]
Hi @vansh-bhatia, I think you might have mixed up the topic with the OP. What is the purpose of getting the header values with the list of rows? They are not part of the results.

**Comment by vansh-bhatia** [comment]
Hi @ozlerhakan, essentially we want to validate the headers and perform operations based on that. Reading the headers is thus a necessary functionality. We can offset by inserting an empty row on top, but wanted to confirm if we have the ability to read the headers.

**Comment by ozlerhakan** [comment]
Hmm, there is no such functionality in place with Poiji :/ However,

> We can offset by inserting an empty row on top, but wanted to confirm if we have the ability to read the headers.

ATM, this can be a workaround, yes.  You can treat the first item in the list as a header by adding the header names to the first row.

**Comment by vansh-bhatia** [comment]
Would you like me to create a PR on this? I'm thinking we could have something like .includeHeaders(true). Would enable functionality for people with my use case.

**Comment by ozlerhakan** [comment]
I would appreciate it, but the thing is, we need to find a uniform structure to handle this case for other types besides string values. If the first item in the list should cover the header names, all data types of fields in this item must be strings, however one might want to use this feature with fields being type of date, and integers.

**Comment by vansh-bhatia** [comment]
Hi @ozlerhakan, 
Valid point. How about something like - 
`
List<String> headersListInOrder = Poiji.getHeadersFromExcel(yourFile,  options);
// perform validations or operations
// Headers with no string can be null or ""
`
Should not break functionality, and would be a good addition to existing functionality. In our case, we read the headers, and then after some validation, we need to export it into another file.

**Comment by ozlerhakan** [comment]
Sounds feasible to have a new method for header specific features. Could you consider taking on this new implementation?

**Comment by vansh-bhatia** [comment]
> Sounds feasible to have a new method for header specific features. Could you consider taking on this new implementation?

I'll try taking it up, but considering I'm not aware of the underlying implementations, it may take some time.

**Comment by vansh-bhatia** [comment]
Hi @ozlerhakan, should I take this up? Any tips how to go about it?

**Comment by ozlerhakan** [comment]
Hi @vansh-bhatia , you might walk through the following method to follow a similar way: https://github.com/ozlerhakan/poiji/blob/23133ca7bc7af0b08638eba5f90092857f165e20/src/main/java/com/poiji/bind/Poiji.java#L155

**Comment by hopdxGms** [comment]
How can I get the header row? it skips my header. I need to take header as a result to make some validation.
