### ISSUE TITLE
com.poiji.exception.PoijiInstantiationException: Cannot create a new instance of aadhar.StudentInfo

### ISSUE THREAD

**Issue by shraddhamehetre10** [ozlerhakan/poiji#165]
Hi there,

I am getting com.poiji.exception.PoijiInstantiationException. when i use Poiji.fromExcel with a fileinput stream. i have attached the project with excel i am using. could you please take a look ?
[aadhar.zip](https://github.com/ozlerhakan/poiji/files/4931262/aadhar.zip)

**Comment by ozlerhakan** [comment]
Hi @shraddhamehetre10 ,

Could you please share your project on GitHub? I can look at it over there

**Comment by ozlerhakan** [comment]
feel free to leave your response here, we can look at it again

**Comment by TriCogz** [comment]
I have the same issues. Here is my upload.
[PoijiExcel.zip](https://github.com/ozlerhakan/poiji/files/12664398/PoijiExcel.zip)
Please let me know if there is something just wrong that I am missing Thanks
