### ISSUE TITLE
Custom validation to Excel headers

### ISSUE THREAD

**Issue by mail2vizzi** [ozlerhakan/poiji#167]
How to perform custom validation on excel headers like ignoring case sensitivity and trimming spaces when using annotations like  @ExcelCellName("ID")

**Comment by ozlerhakan** [comment]
Hi @mail2vizzi , 

You can use the `caseInsensitive()` feature  of the PoijiOptions . trimming spaces are not available for headers. we can support though.

**Comment by mail2vizzi** [comment]
Thanks, could we expect  trimming spaces option for headers in next release?

**Comment by ozlerhakan** [comment]
sure, we can add it :)

**Comment by akashpusolu** [comment]
@ozlerhakan is now this library support trimming spaces when using annotations?

**Comment by ozlerhakan** [comment]
now right now, after release 3.0.1 it will be :)

**Comment by akashpusolu** [comment]
okay thank you
