### ISSUE TITLE
Are we able to create POJO mapping for List<String> columns or String[].Does it support?

### ISSUE THREAD

**Issue by amar212b** [ozlerhakan/poiji#168]
Exception in thread "main" java.lang.IllegalArgumentException: Can not set [Ljava.lang.String; field utility.PoijiPost.Ids to java.lang.String

Getting this error when mapping where i need to pass multiple value given in excel column .
Example : - Column A
                    P,Q

in POJO class we create List<String> ColumnA or String[] Column A.
It doesnt work. Does this library support such mapping

**Comment by ozlerhakan** [comment]
Poiji does not support this format

**Comment by ozlerhakan** [comment]
We can make this possible in the next version @amar212b

**Comment by ozlerhakan** [comment]
we can use List<String>  as a data type of a field in the next release @amar212b
