### ISSUE TITLE
Get Actual Date Value

### ISSUE THREAD

**Issue by chaitut715** [ozlerhakan/poiji#170]
I am trying to read date from excel.
Actual value in excel:07/01/16
formatted value: 07/01/2016

I want to get the actual value(07/01/2016) instead of formatted value .

I tried Feature 11 like below but couldn't make it work:
`PoijiNumberFormat numberFormat = new PoijiNumberFormat();
		numberFormat.putNumberFormat((short) 4, "mm/dd/yyyy");`

Version: 3.0.0
Input file: [poiji-dates.xlsx](https://github.com/chaitut715/share/blob/master/poiji-dates.xlsx?raw=true)

Edit: I want to read as 
07/01/2016

**Comment by ozlerhakan** [comment]
Hi @chaitut715 ,

when I use your test excel file, I get the cell value as "1/7/16", I don't get the formated value like "07/01/2016". I cannot produce the case you mention it

**Comment by chaitut715** [comment]
I want to read as 07/01/2016.
Sorry, if I didn't write clearly.

**Comment by ozlerhakan** [comment]
Ah okay, so you need to `numberFormat.putNumberFormat((short) 14, "dd/MM/yyyy");` not 4. you can check each cell's format using `poijiLogCellFormat` . Please look at as well https://github.com/ozlerhakan/poiji#feature-10 on README. I hope it can help you out

**Comment by chaitut715** [comment]
It worked. Thanks!
