### ISSUE TITLE
Support to read from single sheet instead of a complete excel file

### ISSUE THREAD

**Issue by arrow7Q** [ozlerhakan/poiji#172]
Can we have a support in Poji to read from a sheet and map each row into an object ?

**Comment by ozlerhakan** [comment]
Hi @arrow7Q ,

Interesting, could you share an example for that purpose?

**Comment by arrow7Q** [comment]
Hi,

Suppose we have a workbook having multiple sheets each corresponding to a table(thus a domain object) in database.
And the data from the sheets is needed to update the DB, so each sheet has to be mapped to respective Java objects.

So if we have support to read from single sheet instead of complete workbook, then the above scenario can be handled gracefully.

**Comment by ozlerhakan** [comment]
so do you want something like this: `Poiji.fromExcel(<sheet>)` ?

**Comment by arrow7Q** [comment]
Yes, that would be helpful and add more flexibility in the usage

**Comment by ozlerhakan** [comment]
I see, let's consider to add this feature then :) after analyzing.
