### ISSUE TITLE
Why are the Feature 10 and 11 not bugs ?

### ISSUE THREAD

**Issue by zhfkt** [ozlerhakan/poiji#173]
I am using your Poiji framework to read excel and it gave me lots of conviences. Thanks to the developer.

When I was using this framework, I have the issue and I found this issue is the same described as Feature 10 and Feature 11 on https://github.com/ozlerhakan/poiji.

i.e.

1. In the excel , I found the date format is 2020/9/18

![image](https://user-images.githubusercontent.com/4969804/93878341-7bff8680-fd0c-11ea-9f2d-47e7f0ca508f.png)

2. However, when the Poiji reads and put it into a String , it became the "9/18/20"

![image](https://user-images.githubusercontent.com/4969804/93878463-b23d0600-fd0c-11ea-818b-6292cb86757c.png)

3. I follow the Feature 10 to debug and found the formatString is "m/d/yy". 
![image](https://user-images.githubusercontent.com/4969804/93878968-82dac900-fd0d-11ea-9c74-5c51699a4634.png)

4. So I used the Feature 11 to override the format at index 14,

```java
        PoijiNumberFormat dateFormat = new PoijiNumberFormat();
        dateFormat.putNumberFormat((short) 14, "yyyy/MM/dd");   
```

It indeed works. Now the date printed in Java is 2020/09/18.

I would like to ask: Why the Poiji framework could not automatically detect the date format and apply the correct format on the "2020/9/18" ? Why did I need to maunally debug in Feature 10 and then apply the correct format in Feature 11 on the date format ? I thinkk it feels so weird.

Thank you !

**Comment by ozlerhakan** [comment]
Hi @zhfkt ,

> Why did I need to maunally debug in Feature 10 and then apply the correct format in Feature 11 on the date format ?

Because the number you specify (e.g. 14) could be different depending on an excel file. By default 14 is a built-in format which contain the default date "m/d/yy" format of the excel file structure.

> Why the Poiji framework could not automatically detect the date format and apply the correct format on the "2020/9/18" ?

As I pointed out in the first question, this could be totally different for another excel file. So you need to first monitor a cell and find the number where the cell uses then you can change the default behavior of the cell format by using `PoijiNumberFormat `. 

In any case, if this is a default behavior for all excel format, we can think of changing this option :)

**Comment by zhfkt** [comment]
Thank you for replying.

From your reply, it seems that every excel file will have different index number for the date format. In our system, we need to process different excel files actually instead of only one excel file. If I gave a fixed index 14 here, is it in risk for our system to apply the "yyyy/MM/dd" to the other (not date) cell format for the other excel files ? Will it cause the protential bug for the other excel file which may not be the same format type in index 14 if I gave a fixed index number 14 in the code here ?

**Comment by ozlerhakan** [comment]
I should correct myself, 14 is reserved number for "m/d/yy" so you only change the format of date format of 14. I think if you give a fixed index 14 and you only change the format behavior of 14 that is it. It shouldn't exhibit a risk for my perspective

**Comment by zhfkt** [comment]
Thank you for confirmation.

I suggest you could mentioned "14 is reserved number" on the main page of wiki as well.

**Comment by zhfkt** [comment]
I also hope maybe there is an internal method to set the format of the date instead of manualy runing the code "dateFormat.putNumberFormat((short) 14, "yyyy/MM/dd");   " if the '14' is a fixed index for all excel files.

**Comment by ozlerhakan** [comment]
let's keep it here, we can find a way if this option is requested more

**Comment by ozlerhakan** [comment]
for now we can close this task, we can re-open it once we get interactions about the content
