### ISSUE TITLE
Missing first row when using header and skip options.

### ISSUE THREAD

**Issue by alicanozer** [ozlerhakan/poiji#177]
if i set options like this:
PoijiOptions options = PoijiOptions.PoijiOptionsBuilder
                .settings(1)//I CAN NOT SET TO 0
                .sheetIndex(sheetIndex)
                .build();

I am missing the first row after header row. Maybe because of this line:
public static PoijiOptionsBuilder settings(int skip) {
            if (skip <= 0) {
                throw new PoijiException("Poiji already skips the header. Skip index must be greater than 1");
            }
            return new PoijiOptionsBuilder(skip + 1);//THIS LINE
        }

**Comment by ozlerhakan** [comment]
Hi @alicanozer ,

Do you want to skip the first record of the data?

**Comment by alicanozer** [comment]
Hi Hakan,

I only want to skip header row and i also want to choose sheet index, how can i do this. if i want to use options it automatically skip the first row(after header)

**Comment by ozlerhakan** [comment]
this should works fine : 
```
PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings().headerStart(-1).sheetIndex(sheetIndex).build();
```

**Comment by ozlerhakan** [comment]
feel free to leave your comment here, if you need further help, thank you
