### ISSUE TITLE
HSSFUnmarshaller does not release locks from the file

### ISSUE THREAD

**Issue by acoj1993** [ozlerhakan/poiji#182]
Hi,

I have a use case, where I would move a file from one directory to another after I read the data using your library. 
However, when I input an XLS file, I am unable to delete the file. This does not happen when I input an XLSX file.

Am I right that the HSSFUnmarshaller does not release locks from the file?

**Comment by ozlerhakan** [comment]
Hi @acoj1993 ,

Interesting, we have different test cases with xlsx and xls files. They do not produce such a problem. I will be pleased If you take a look at the problem via PR

**Comment by acoj1993** [comment]
Ok, I will see what I can do.

**Comment by acoj1993** [comment]
Hi again,

sorry for not posting back to this issue, but I was extremely busy and could not get the chance to take a look at the problem.
Here is, however, a code snipped of how you can reproduce the problem.


```
public class Test {

    public static void main(String[] args) {
        File xlsFile = new File("<ABS_PATH>/people.xls");
        List<Person> people = Poiji.fromExcel(xlsFile, Person.class);
        try {
            FileUtils.forceDelete(xlsFile);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

@Getter
@Setter
public class Person {

    @ExcelCell(0)
    private String firstName;

    @ExcelCell(1)
    private String lastName;
}

```
