### ISSUE TITLE
Feature 16 not available for sheet

### ISSUE THREAD

**Issue by prabhatsir** [ozlerhakan/poiji#184]
Could you please disclose the actual version of latest release since the last feature 16(passing sheet as parameter) is very much unavailable to me.

**Comment by ozlerhakan** [comment]
Hi @prabhatsir ,

README shows all the features users can benefit from, you can look at https://github.com/ozlerhakan/poiji/releases for the latest changes.

**Comment by prabhatsir** [comment]
I would like to know the point of passing sheet when options provide a similar feature and when this feature does not seem helpful after removeCell() of duplicate headers

**Comment by ozlerhakan** [comment]
You can ask here for more info https://github.com/ozlerhakan/poiji/issues/172 since this was a request. Each excel header must be unique.

**Comment by prabhatsir** [comment]
Fine then if you insist in my virtual sheet I will go ahead with deleting all the columns as well, under the repeated headers.

**Comment by prabhatsir** [comment]
Fine then if you insist in my virtual sheet I will go ahead with deleting all the columns as well, under the repeated headers.
