### ISSUE TITLE
ClassCastException Issue

### ISSUE THREAD

**Issue by anandh51295** [ozlerhakan/poiji#192]
I am getting this error java.lang.ClassCastException: org.apache.poi.xssf.usermodel.XSSFWorkbook cannot be cast to org.apache.poi.hssf.usermodel.HSSFWorkbook

**Comment by ozlerhakan** [comment]
Hi @anandh51295 ,

Could you please past the stack trace and the steps you produce?

**Comment by ozlerhakan** [comment]
feel free to leave a comment, since it is idle, I'm closing it
