### ISSUE TITLE
preferNullOverDefault not working for Date

### ISSUE THREAD

**Issue by ketan2505** [ozlerhakan/poiji#195]
I am not able to get default values as mentioned in below code snippet when excel sheet contains alphabet characters in `valid_from` and `valid_to` columns Ex. abcd,  NA etc.

```
  @ExcelCellName("Valid_From")
  @Column(name = "Valid_From")
  private Date validFrom = new GregorianCalendar(2000, Calendar.JANUARY, 1).getTime();

  @ExcelCellName("Valid_Till")
  @Column(name = "Valid_Till")
  private Date validTill = new GregorianCalendar(2099, Calendar.DECEMBER, 1).getTime();

```

And these are poijiOptions I am using- 
```
PoijiOptions.PoijiOptionsBuilder.settings()
        .datePattern("yyyyMM")
        .dateLenient(false)
        .preferNullOverDefault(false)
        .build();
```

When excel sheet has blank columns (`valid_from` and `valid_to` ), default values appear in result object. However when I put invalid data like `abcd` in date columns, I get current date in result - It should either give default date or some exception.

**Comment by ozlerhakan** [comment]
@ketan2505 , 

It actually throw an exception and return the current date:
https://github.com/ozlerhakan/poiji/blob/398d2e10a8b4011f17f3b49df65e656b7e4e8b8e/src/main/java/com/poiji/config/DefaultCasting.java#L167
