### ISSUE TITLE
Read empty rows

### ISSUE THREAD

**Issue by samhalpa** [ozlerhakan/poiji#2]
I have a xlsx file which contains only 100 filled rows. (2 columns). This file was created from a google spread sheet. When I try to convert those rows into an object using Poiji, it converts an empty rows as well.
By default sheet has 1000 rows. Out of those 1000 rows only 100 rows contains data. (in 2 columns). But after converting to objects I get 1000 objects.
Is there anyway that it can stop reading the rows once it found an empty row?

**Comment by ozlerhakan** [comment]
Hi @samhalpa ,

Thank you for bringing this up!, could I have your mentioned excel file to improve the current test cases?

**Comment by samhalpa** [comment]
Hi @ozlerhakan 
Please download the file from following link:
https://docs.google.com/spreadsheets/d/1fsbLSIAXZCmeOEjVUyiizwkEKUSlG_s3JrSORKkZi0E/edit?usp=sharing

**Comment by ozlerhakan** [comment]
Thanks @samhalpa , the new release i.e. 1.2 should be available today, i guess
