### ISSUE TITLE
CastingTest incorrect

### ISSUE THREAD

**Issue by blaketastic2** [ozlerhakan/poiji#20]
It appears that in the CastingTest.java, the "castValue" is passed Object types, instead of primitive types. This causes the "castValue" to not even hit the conditions for anything other than "java.util.Date". An easy work around would be to change to the primitive implementation, however, the tests will need to be re-written.

**Comment by ozlerhakan** [comment]
Hi @blaketastic2 ,

Thank you for examining and bringing this up. I will look at the mentioned test class.

**Comment by ozlerhakan** [comment]
I have changed the way of passing the primitive types at [1.8](https://github.com/ozlerhakan/poiji/blob/4146d7f788a672872b633194762650c49d2325f1/src/test/java/com/poiji/util/CastingTest.java) branch for the CastingTest class. you can take a look at it.

**Comment by ozlerhakan** [comment]
Your changes live on the new version 1.8, thanks again.
