### ISSUE TITLE
Hi, can it be used with kotlin? 

### ISSUE THREAD

**Issue by cvargasr31** [ozlerhakan/poiji#206]
I just want to read data from excel using kotlin so I want to know if I can use this library. If so can you provide a quick example?

PD: I have been using this with java, awesome library!

**Comment by ozlerhakan** [comment]
Hi @cvargasr31 ,

Thank you for your support first off.

You can use Poiji once you add the Poiji dependency to the pom.xml of a Kotlin project. Here is a snippet written in Kotlin:

```
val employees = Poiji.fromExcel<Employee>(File("employees.xls"), Employee::class.java)
```

**Comment by cvargasr31** [comment]
thanks for the response, that works if the class is also written with kotlin instead of java?
