### ISSUE TITLE
Having mandatory and optional Columns

### ISSUE THREAD

**Issue by ozlerhakan** [ozlerhakan/poiji#207]
### Discussed in https://github.com/ozlerhakan/poiji/discussions/203

<div type='discussions-op-text'>

<sup>Originally posted by **bhelemilan** August 11, 2021</sup>
With **namedHeaderMandatory** option set to true, if we use **@ExcelCellName** annotation, the field is mapped to respective column in excel sheet and becomes a mandatory.

Can it be extended to have some optional columns? 

Example: An Excel sheet has 10 columns out of which 8 are mandatory and 2 to be optional. That means, we should be able to parse excel sheet with only 8 mandatory columns and with/without other 2 optional columns.</div>

**Comment by vaa25** [comment]
@bhelemilan You can use mandatory option in [Poiji2](https://github.com/vaa25/poiji2)

**Comment by ozlerhakan** [comment]
you can use Poiji 3.1.2 @bhelemilan  Thanks! 

Please refer to https://github.com/ozlerhakan/poiji#optional-mandatory-columns to make use of.
