### ISSUE TITLE
Issue with Negative numbers

### ISSUE THREAD

**Issue by savinaysinha** [ozlerhakan/poiji#208]
In my excel we have some coulmns that can be negative, but while converting excel into pojo, it assigns 0 instead of negative number:

let say my excel is this :

![image](https://user-images.githubusercontent.com/47267136/133193602-15fd2270-d7cc-43a1-ba56-4da40821a42f.png)

values column contains negative and positive numbers.

this is pojo class
![image](https://user-images.githubusercontent.com/47267136/133193721-3e4c5703-84dc-4144-a66b-f9c757dc51fa.png)

and the output I am getting is like this 

![image](https://user-images.githubusercontent.com/47267136/133194169-ada0a89a-05ff-4a7a-8af2-28ac193bb647.png)

Is there something I am missing out or doing it wrong?

**Comment by ozlerhakan** [comment]
Hi @savinaysinha ,

Thank you bringing this up. I will take a look at this case.

**Comment by vaa25** [comment]
@savinaysinha  You can use [Poiji2](https://github.com/vaa25/poiji2). It works with negative numbers properly.

**Comment by ozlerhakan** [comment]
Hi again @savinaysinha ,

I couldn't reproduce this problem with both xls and xlsx excel formats. BTW **you should use float not long if you have decimal numbers.** Feel free to add you comments If you have still this problem.

all the best
