### ISSUE TITLE
support trimming over list

### ISSUE THREAD

**Issue by ashishchoksi** [ozlerhakan/poiji#210]
I have a column in excel with value => `"abc,      pqr,  xyz"` (multiple spaces in between)

I am capturing it as a list in my POJO.

@ExcelCellName("col)
List<String> col;

result =` ["abc","       pqr","  xyz"]` (multiple space included )

it would be great if we support trim over list also,
or if it is already here please tell me what option I need to set.

Thank you.

**Comment by ozlerhakan** [comment]
Hi @ashishchoksi ,

Thank you for your advice! We need to update https://github.com/ozlerhakan/poiji/blob/398d2e10a8b4011f17f3b49df65e656b7e4e8b8e/src/main/java/com/poiji/config/DefaultCasting.java#L216 

Feel free to create a PR if you want to contribute to Poiji :)

**Comment by vaa25** [comment]
@ashishchoksi You can use PoijiOptions.PoijiOptionsBuilder.settings().addListDelimiter("\s*,\s*").build() to remove all spaces between delimiter and values

**Comment by ozlerhakan** [comment]
you can use Poiji 3.1.2 @ashishchoksi  thanks!
