### ISSUE TITLE
Poji changed String 3/30/2021  to 3/30/21 

### ISSUE THREAD

**Issue by vaquarkhan** [ozlerhakan/poiji#212]
I have date 3/30/2021 which i am reading as String using Poji when its coming into POJO its coming like 3/30/21 .
Now issue is  when i convert this 3/30/21 . to java.sql.date before store into MYSQL its coming like  0021-03-30.

How can i read full 3/30/2021 using poji ?

**Comment by ozlerhakan** [comment]
Let me understand clearly, you have a date column and you map it as String as follows:

```
@ExcelCellName("COLUMN_DATE")
String date;
```

and you get the value as "3/30/21" right?

Normally It shouldn't be this way since it's of type String. Could you give me examples?

**Comment by vaquarkhan** [comment]
I have date column in xlsx 
![image](https://user-images.githubusercontent.com/3491908/141320547-2f78949e-eef7-451d-810b-82e7042d6450.png)

Now here is my POJO 

      @ExcelCell(21)
	String startDate;
	@ExcelCell(22)
	String endDate;
	
**Service code :**
      List<Resource> resource = Poiji.fromExcel(new File(SAMPLE_XLSX_FILE_PATH), Resource.class);

Once list populated i am sending into Springboot Repository and inside calling JDBC template to insert records 
So when going to insert i am converting this String date to Java.sql.date and insert.

SInce Poiji reading 3/30/21 conversion adding junk values into db
![image](https://user-images.githubusercontent.com/3491908/141321481-cbc366c3-5d58-4e2b-99f6-bf47d6da7225.png)

**Comment by ozlerhakan** [comment]
Could you please share with me an excel file with those few examples?

**Comment by vaquarkhan** [comment]
You can try with this data
![image](https://user-images.githubusercontent.com/3491908/141334334-66f41439-9a69-45fc-b571-47d8df924f85.png)

**Comment by ozlerhakan** [comment]
I need your sample excel file @vaquarkhan , otherwise I tried but couldn't produce this case for the date values like '3/30/2021'

**Comment by vaquarkhan** [comment]
[sample.xlsx](https://github.com/ozlerhakan/poiji/files/7523036/sample.xlsx)
here you go

**Comment by ozlerhakan** [comment]
Thanks @vaquarkhan , Now I see that there is a style in these columns and poi by itself gets their format index as 14 and theirs format string as 'm/d/yy'. You can debug all the cells of an excel file via https://github.com/ozlerhakan/poiji#debug-cells-formats.

What you need to do is you can convert the format string of the format index via https://github.com/ozlerhakan/poiji#modify-cells-formats.

You can use these steps:
```
PoijiNumberFormat numberFormat = new PoijiNumberFormat();
numberFormat.putNumberFormat((short) 14, "dd/mm/yyyy");

PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings()
        .poijiNumberFormat(numberFormat)
        .build();
```

and here it is:

<img width="609" alt="Screen Shot 2021-11-12 at 9 08 34 AM" src="https://user-images.githubusercontent.com/1964927/141418776-f270a258-2231-4eb9-92b0-72e2ccd2821a.png">

BTW when I opened it up on my local the columns look like this:

<img width="524" alt="Screen Shot 2021-11-12 at 8 25 30 AM" src="https://user-images.githubusercontent.com/1964927/141416421-18154834-65ca-43dc-8ad5-a0c8d33c8762.png">

**Comment by vaquarkhan** [comment]
Thanks let me check

**Comment by ozlerhakan** [comment]
you can use 3.1.3 of Poiji @vaquarkhan , thank you for your contribution :)
