### ISSUE TITLE
Issue in regards to Discussion #203

### ISSUE THREAD

**Issue by bhelemilan** [ozlerhakan/poiji#225]
Tested with v 3.1.5: Expected **HeaderMissingException** but not thrown (instead assigned with null value).

With v 3.1.2+, since **namedHeaderMandatory option** has been removed, I annotated with **@ExcelCellName("columnName")** (mandatory attribute set to true, as per documentation), and the column is missing from excel file.

Expecting **HeaderMissingException** to be thrown, but instead **null** value is assigned.

**Comment by ozlerhakan** [comment]
Hi @bhelemilan ,

Thank you for using Poiji first off. Could you share with me the code and a sample of your excel file?
