### ISSUE TITLE
Handling of multiple sheets data

### ISSUE THREAD

**Issue by hendryang** [ozlerhakan/poiji#227]
Hello @ozlerhakan and team.

Is it possible to retrieve data from multiple sheet into single object? Sample usage :
``` java
@ExcelSheet("SheetA", "SheetB", "SheetC")
public class ConsolidatedModel {

    @ExcelCellName("Name")  // assume SheetA has column Name. If other sheet also has same column name, column from first sheet will be taken.
    private String nameFromA;

    @ExcelCellName("Age") // assume SheetB has column Age
    private int ageFromB;

    @ExcelCellName("Email") // assume SheetC has column Email
    private String emailFromC;
}
```
Thank you

**Comment by ozlerhakan** [comment]
Hi @hendryang ,

Poiji does not support multiple sheets. What you can do is you can get the data from each sheet and combine them into one data model with regard to your business need for now. 

Once you decide what the correct approach should be for this purpose, feel free to make  a PR :)
