### ISSUE TITLE
extrange wrong error when disableXLSXNumberCellFormat is true

### ISSUE THREAD

**Issue by dacopan** [ozlerhakan/poiji#234]
Currently when try parse attached files we have a error on parse number cells 
1. java.lang.NullPointerException: Cannot invoke "String.length()" because "address" is null
2. java.lang.ArrayIndexOutOfBoundsException: Attempt to modify attribute at illegal index: 5

[autos2.xlsx](https://github.com/ozlerhakan/poiji/files/8376654/autos2.xlsx)
[autos3.xlsx](https://github.com/ozlerhakan/poiji/files/8376655/autos3.xlsx)

After exhaustive debuggin I can find that when https://github.com/ozlerhakan/poiji/blob/65a9395cd55cf65436ad114a07b65357079685c4/src/main/java/com/poiji/bind/mapping/XSSFSheetXMLPoijiHandler.java#L59
this line run, somethings extrange and errors occurs after pass this line

**Comment by ozlerhakan** [comment]
Hi @dacopan , 

I'll look at the problem, thank you!

**Comment by ozlerhakan** [comment]
can you share your entity model as well @dacopan ?

**Comment by dacopan** [comment]
Hi, sorry by the late, this is my Entity, `UqaiExcelBase` has only `rowIndex`
please tell me if you need more info

```java
package com.uqai.excelutil.dto;

import com.poiji.annotation.ExcelCell;
import com.poiji.annotation.ExcelCellName;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * @author dacopan on 19/3/22
 */
public class AutoImport extends UqaiExcelBase {

    //marca	modelo	cilindraje	fabricacion	activo	valor	celular
    @ExcelCellName(value = "fabricacion", mandatory = false)
    private LocalDate fecha;

    @ExcelCell(0)
    private String clase;

    @ExcelCell(1)
    private String tipo;

    @ExcelCell(2)
    private String subtipo;

    @ExcelCell(3)
    private String marca;

    @ExcelCell(4)
    private String modelo;

    @ExcelCell(5)
    private String submodelo;

    @ExcelCell(6)
    private String dsc;

    @ExcelCell(7)
    private Double pmercado;

    @ExcelCell(8)
    private Double ptoma;

    @ExcelCell(9)
    private String anio;

    @ExcelCell(10)
    private String cil;

    @ExcelCell(11)
    private String com;

    @ExcelCell(12)
    private String tp;

    @ExcelCell(13)
    private Integer pasajeros;

    @ExcelCell(14)
    private Integer puertas;

    // todo Zonedateime
    // todo BigDecimal

}
```

**Comment by dacopan** [comment]
please see this repo https://github.com/dacopan/poiji-error-demo
in Test package you can change `autos2` and `autos3` both show strange error derivated of the reported error
Note.- Sorry by the bad code, it's a starter library I'm testing

**Comment by ozlerhakan** [comment]
thank you @dacopan , I see what It causes!

**Comment by ozlerhakan** [comment]
Hi @falko , could you please share with me your excel file and model class?
