### ISSUE TITLE
Mechanism is required to get column values by header names

### ISSUE THREAD

**Issue by abdulrafique** [ozlerhakan/poiji#24]
Mechanism is required to get column values by header names.

For Example:
Expected header format is:
id name
Actual:
name id

We don't have mechanism to specify it is invalid format, we can only read by annotation as:
@ExcelCell(0)
int id;

@ExcelCell(1)
String name;

So if we have an excel in format:
name id

I think we should also have mechanism to read by header name:

@ExcelCellName("id")
int id;

@ExcelCellName("name")
String name;

**Comment by ozlerhakan** [comment]
We can add this feature plainly in the process of `.xls` file, however, I am not sure how to make this possible if an excel file is of format `.xlsx`.

**Comment by nwarriorch** [comment]
Why not parse the first row and match it with the pattern provided? how would it look like in .xls?

**Comment by ozlerhakan** [comment]
You're right @nwarriorch , this could be the solution path for types of `.xlsx`

**Comment by ozlerhakan** [comment]
1.11 enables to make this possible with the both excel types now. Thank you @nwarriorch , @abdulrafique
