### ISSUE TITLE
Repeated columns in @ExcelCellRange

### ISSUE THREAD

**Issue by furoraru** [ozlerhakan/poiji#244]
Hi!

Suppose, I have a table with repeated nesting:

<table><thead><tr><th rowspan="2">Type</th><th colspan="3">June</th><th colspan="3">July</th></tr><tr><th>Plan</th><th>Delta</th><th>Sum</th><th>Plan</th><th>Delta</th><th>Sum</th></tr></thead><tbody><tr><td>type 1</td><td>1</td><td>1</td><td>2</td><td>1</td><td>2</td><td>3</td></tr><tr><td>type 2</td><td>2</td><td>2</td><td>4</td><td>3</td><td>2</td><td>5</td></tr></tbody></table>

Is there anything that can be done to make something like this to get pojo?

```
public class FilePojo {
    @ExcelCellName("Type")
    private String type;

    @ExcelCellName("June")   ----- use to find out the heading in which we will look for subheadings
    @ExcelCellRange()
    private Month june;

    @ExcelCellName("July")
    @ExcelCellRange()
    private Month july;

    public static class Month {
        @ExcelCellName("Plan")
        private Integer plan;

        @ExcelCellName("Delta")
        private Integer delta;

        @ExcelCellName("Sum")
        private Integer sum;
    }

}
```

**Comment by furoraru** [comment]
Or maybe 

```
public class FilePojo {
    @ExcelCellName("Type")
    private String type;

    @ExcelCellRange("June")   ----- use to find out the heading in which we will look for subheadings
    private Month june;

    @ExcelCellRange("July")
    private Month july;

    public static class Month {
        @ExcelCellName("Plan")
        private Integer plan;

        @ExcelCellName("Delta")
        private Integer delta;

        @ExcelCellName("Sum")
        private Integer sum;
    }

}
```

**Comment by ozlerhakan** [comment]
Hi @furoraru ,

You give different names for each headers line PlanA | DeltaA | SumA | PlanB | DeltaB | SumB. You can look at this test https://github.com/ozlerhakan/poiji/blob/master/src/test/java/com/poiji/deserialize/DeserializeByCellRangeTest.java
