### ISSUE TITLE
Mechanism required to input file streams instead of files. 

### ISSUE THREAD

**Issue by nwarriorch** [ozlerhakan/poiji#25]
In the current mechanism. If the file is in memory as a byte stream there is no way around committing it to a file system. It'll be great if we can have a constructor that takes file stream as an input.

**Comment by ozlerhakan** [comment]
We are able to do it now as follows:

```
InputStream stream = new FileInputStream(new File("employees.xls"))
List<Employee> employees = Poiji.fromExcel(stream, PoijiExcelType.XLS, Employee.class, options);

```
