### ISSUE TITLE
Impossible to map values in reused @ExcellCellRange classes

### ISSUE THREAD

**Issue by loic-roux-404** [ozlerhakan/poiji#261]
I have massive xlsx file mapping multiple `@ExcelCellRange` to a class. In my class i'm using many times the same static class and i cant map columns taking care of previous ones so poiji always give 1,2,3,4 columns values .

```java
     */
    @Getter
    public static class Clud {
        @ExcelCell(0)
        private Boolean list;
        @ExcelCell(1)
        private Boolean create;
        @ExcelCell(2)
        private Boolean update;
        @ExcelCell(3)
        private Boolean delete;
    }
```

```java
    @ExcelCellRange
    @ExcelCellName("Accueil externe - thème")
    private Clud externalRoutingTheme;

    @ExcelCellRange
    @ExcelCellName("Accueil externe - list")
    private Clud externalRoutingList;

```

It's currently imopossible to map correctly ranges because the unmarshaler consider every cell on their line and not caring about parent excel range. So here with a data set like this :

```
|  Accueil externe - thème                       |  Accueil externe - list                               |
| Voir la list | Créer |Modifier | Supprimer |Voir la list | Créer |Modifier | Supprimer | 
| TRUE  | FALSE  | TRUE   | TRUE   |  FALSE | FALSE   |  FALSE | FALSE  |
```

Giving : 
- externalRoutingTheme: Clud{TRUE  , FALSE  , TRUE   ,TRUE}
- externalRoutingList: Clud{TRUE  , FALSE  , TRUE   ,TRUE}

With any next column after first using this class Clud it will be mapped to first columns 1,2,3,4. `externalRoutingList == externalRoutingTheme`
We have the same behaviour with `@ExcelCellName` reused inside multiple ExcelCellRange static class. Poiji is always taking first @ExcelCellName with a name present in others.

**Comment by loic-roux-404** [comment]
I can try to make a PR. It's look like a complex features inside many recursions...

**Comment by ozlerhakan** [comment]
Hi @loic-roux-404 , Feel free to make your changes for the ExcellCellRange annotation. We could find a preferable way to make a column unique for this occasion.

**Comment by loic-roux-404** [comment]
Yes i said that without knowledge of the @ExcelCellRange part. I'm going to draft something

**Comment by loic-roux-404** [comment]
Sorry i haven't enough time to research the code for now bu i will try to do it next week.
