### ISSUE TITLE
LocalDate is always parsed to current date

### ISSUE THREAD

**Issue by ankit030287** [ozlerhakan/poiji#267]
Hi,

This is the part of my model
```
  @ExcelCellName("StartDate")
  private LocalDate startDate;
```

This is how I am using it
```
PoijiOptions options = PoijiOptionsBuilder.settings()
        .datePattern("dd/MM/yyyy")
        .sheetIndex(sheetIndex)
        .build();

    try {
      return Poiji.fromExcel(inputStream, PoijiExcelType.XLSX, clazz, options);
    } 
```

All the fields are correctly parsed but the startDate field is always getting parsed to current date. Attaching the screenshot for excel file

<img width="422" alt="image" src="https://user-images.githubusercontent.com/36099373/212521302-d667965b-cd49-46af-a83e-4cb7434cfa09.png">

Am I missing anything?

**Comment by ankit030287** [comment]
Found out that its the duplicate of https://github.com/ozlerhakan/poiji/issues/166 so closing tis

**Comment by ankit030287** [comment]
Would it be possible to not use current date by default as it will lead to issues we won't know?

**Comment by StephenR-Softcom** [comment]
Hi, I had the same issue at first because the Excel date format was not what it looked like (it's not what's written in the formula bar).

In your Excel sheet, check the cell format for a StartDate field and specify that date format in the Poiji Options
