### ISSUE TITLE
Can we read encrypted excels using poiji?

### ISSUE THREAD

**Issue by abdulrafique** [ozlerhakan/poiji#28]
Can we read encrypted excels using poiji?

We have excels which are password protected and I need to read them.

**Comment by ozlerhakan** [comment]
Currently, It's not supported. But we can find a way to do it https://poi.apache.org/encryption.html

**Comment by ozlerhakan** [comment]
Of course @nwarriorch, I appreciate that

**Comment by nwarriorch** [comment]
@ozlerhakan great! assign me the ticket and I shall update here as I progress.

**Comment by ozlerhakan** [comment]
right now I cannot assign you. once you contribute the project, you'll be assignable, I guess

**Comment by nwarriorch** [comment]
No issues. Will create a pull request when I am done.

**Comment by abdulrafique** [comment]
Do we have capability now for encrypted excels.

**Comment by ozlerhakan** [comment]
Did you make any progress for this case @nwarriorch ?

**Comment by ozlerhakan** [comment]
Hi @abdulrafique ,

We are able to read encrypted files as of 1.13. Could you please try it out?

**Comment by ozlerhakan** [comment]
feel free to drop a message here for the feature.
