### ISSUE TITLE
Potential IAE with 4.1.1 due to deprecation fix

### ISSUE THREAD

**Issue by DManstrator** [ozlerhakan/poiji#282]
In commit ca30938082e1d03758aa6a2487a80c39916593a6, `Constructor#isAccessible` was replaced by `Constructor#canAccess(null)`. From what I've seen [within the source code](http://www.java2s.com/example/java-src/pkg/java/lang/reflect/accessibleobject-86590.html), this could raise an `IllegalArgumentException` since `null` is treated as an invalid value.

I honestly don't know what else could be used but I wanted to point it out.

**Comment by ozlerhakan** [comment]
Hi @DManstrator , I was aware of that case. I was thinking that this unlikely happen to have while debugging the code.

**Comment by DManstrator** [comment]
I looked at the source code again and searched for example usages. The examples also use `null` as the param and by looking closely, the method can also throw for non-null usages. So I guess it is correct in this case, sorry for the inconveniences.
