### ISSUE TITLE
Not able to read by Column name if the header starts from row x

### ISSUE THREAD

**Issue by abdulrafique** [ozlerhakan/poiji#29]
Not able to read by Column name if the header starts from row x

I have to start reading the rows from row 6, so I have specified my headers at row 5, but using version 1.11, I am not able to read such scenario by column name.

 @ExcelCellName("Currency")
    private String currency;

    @ExcelCellName("No")
    private String no;

Config Class:
 @Bean(name = "poijiOptionsSMBQ")
    public PoijiOptions genericOptions() {
        return settings(6).sheetIndex(0).build();
    }

**Comment by ozlerhakan** [comment]
For a workaround, just put the header in the first row, we need an option to specify it, otherwise, no one can know where the header is in the excel.

**Comment by abdulrafique** [comment]
I think if we are reading from n row as part of poiji options then it's safe to assume n-1 as header

**Comment by ozlerhakan** [comment]
hmm, this is not a general case though

**Comment by abdulrafique** [comment]
Or can we say where the header is in poiji options to support reading by header names for scenarios where header is at (n-1)

**Comment by zhouyixiang** [comment]
It will be awesome if this option can be added. Header row should be as close as to the data rows, above the header we could provide hints or something else related in the template.

**Comment by ozlerhakan** [comment]
This is available as of 1.19. You can use the `headerStart` method to specify the position at where the header starts.
