### ISSUE TITLE
Reading Excel With japanese character, that include phonetic text 

### ISSUE THREAD

**Issue by huatam391** [ozlerhakan/poiji#290]
Currenly i'm using v4.1.1
When parse value from excel .xlsx format to java class, i got problem if cell value is japanese character, it will read cell value include phonetic text at end of string
![image](https://github.com/ozlerhakan/poiji/assets/47975436/feaeb88a-d875-4e55-acc5-79f28c424c0b)
Expect:
companyNm: 株式会社日工
branchNm: 大阪名古屋工場
But actual:
company: 株式会社日工
branchNm: 大阪名古屋工場 オオサカ ナゴヤ コウジョウ
Result of branchNm include furigana at the end of string

**Comment by ozlerhakan** [comment]
Hi @huatam391 ,

Thanks for sharing this situation with us! It's very strange behavior I see here, perhaps there is something hidden in the file you use or this intentionally behaves differently. Could you share your file, so I can investigate the issue?

**Comment by huatam391** [comment]
[フォーマット_インポート：宿泊施設 (1).xlsx](https://github.com/ozlerhakan/poiji/files/12449579/_.1.xlsx)
@ozlerhakan  this file is here, i think this issue happen cause new feature phonetic of excel (support furigana for Japanese character).

**Comment by ozlerhakan** [comment]
Sadly, I'm not able to open your excel properly using the numbers app on my mac. Feel free to create a PR with the fix for your case!
