### ISSUE TITLE
com.poiji.exception.PoijiInstantiationException: Cannot create a new instance of aadhar.StudentInfo

### ISSUE THREAD

**Issue by TriCogz** [ozlerhakan/poiji#293]
https://github.com/ozlerhakan/poiji/issues/165 I have the same issue. I put a comment on the ticket which is closed so I am not sure if the info still notifies. So opening this ticket. Same infor.
[PoijiExcel.zip](https://github.com/ozlerhakan/poiji/files/12676607/PoijiExcel.zip)

**Comment by ozlerhakan** [comment]
You don't need a constructor for TestDataAllTestCasesP please look into Poiji tests on how to create Entity classes to use them in Poiji. https://github.com/ozlerhakan/poiji#annotations
