### ISSUE TITLE
When I set up headerCount with 0, @ExcelUnknownCells does not parse correctly

### ISSUE THREAD

**Issue by baov** [ozlerhakan/poiji#294]
Hello,

When I set up headerCount with 0, @ExcelUnknownCells does not parse correctly

![image](https://github.com/ozlerhakan/poiji/assets/7372496/9bc93e6f-587f-490e-a493-ec14fb67fe9e)

I guess that you need at least header to work fine.

Thanks for your help.

notes : 
- com.poiji.deserialize.UnknownCellsIdenticalHeadersTest#byIndex
- src/test/resources/unknown-cells-identical-headers.xlsx

**Comment by ozlerhakan** [comment]
Hi @baov , 

When `headerCount` is set to 0, the header is treated as a data row. Plus, the annotation requires a header.

**Comment by ozlerhakan** [comment]
You can use v4.1.2 for the mentioned use case @baov !

**Comment by baov** [comment]
Thank you @ozlerhakan
