### ISSUE TITLE
How can I ignore external workbook references in formula

### ISSUE THREAD

**Issue by abygladiator** [ozlerhakan/poiji#296]
I'm using v3.1.0 and my worksheet has an external workbook reference in the formula for range of cells. When I'm trying to use Poiji.fromExcel and pass the sheet and options, I'm getting the exception "could not resolve external workbook name ... Workbook environment has not been setup".

Will you please suggest the best way to resolve this issue?

Thanks

**Comment by ozlerhakan** [comment]
Hi @abygladiator , we could apply this [solution](https://stackoverflow.com/a/65663403) for your use case. Could you share the file your have with me, so we can add a test for this as well for the next release of Poiji?

**Comment by ozlerhakan** [comment]
Sorry but I need a sample like the one you have to try it out.

**Comment by abygladiator** [comment]
See the two files Test-01 refers to the values in Test-02. Assume Test-02 is somewhere in the cloud and you have the URL for the physical document referenced in the Test-01 file
[Test-01.xlsx](https://github.com/ozlerhakan/poiji/files/13311453/Test-01.xlsx)
[Test-02.xlsx](https://github.com/ozlerhakan/poiji/files/13311454/Test-02.xlsx)

**Comment by ozlerhakan** [comment]
I haven't checked it yet. Ping it for the stale bot

**Comment by abygladiator** [comment]
Can you look at it please? Let me know if you need more input

**Comment by ozlerhakan** [comment]
Hi @abygladiator , 

I couldn't reproduce this using 4.1.2.

**Comment by abygladiator** [comment]
Are you saying version 4.1.2 supports reading the worksheet values with vlookup and other formula types?

**Comment by ozlerhakan** [comment]
I was able to read the cells in the excel files with no exception. What do you exactly aim when you correctly read your files using Poiji?

**Comment by abygladiator** [comment]
Yes, I want to read the cell values and convert the sheet data to the mapper class. However, this line 
List data = Poiji.fromExcel(sheet, mapper, options);
throws "could not resolve external workbook name ... Workbook environment has not been setup" exception

**Comment by ozlerhakan** [comment]
Either https://github.com/ozlerhakan/poiji?tab=readme-ov-file#poi-sheet-support or https://github.com/ozlerhakan/poiji?tab=readme-ov-file#annotations works without the exception you point out. Make sure you're using the latest version of Poiji

**Comment by ozlerhakan** [comment]
Did you figure it out @abygladiator ?

**Comment by abygladiator** [comment]
I tried to use version 4.2.1and run it iwith gradle 6.5 but I'm getting the following error:

"Could not resolve all files for configuration ':compileClasspath'.
Could not find com.github.ozlerhakan:Poiji:4.2.1."

Is it possible to run the new version with gradle 6.5?

**Comment by ozlerhakan** [comment]
Interesting.. this shouldn't be related to gradle version. Could you clean your project and add poiji from scratch?

**Comment by abygladiator** [comment]
Still same issue
