### ISSUE TITLE
Hi can u help  for the attached excel is it possible to convert it as pojo ?

### ISSUE THREAD

**Issue by venkatagopiunnamNW** [ozlerhakan/poiji#301]

**Comment by ozlerhakan** [comment]
What have you done so far?

**Comment by venkatagopiunnamNW** [comment]
> What have you done so far?

So far i read above excel file through poiji steps in java.If u observe in above excel sheet SourceTablename-->Contains multiple Source column and target names..etc.Without using delimeter(, or ;)is it possible to read through pojo like 
class  emp {
private String sourceTableName;
private List<String> sourceColumnname;
private List<String> targetColumnName;
}
@ozlerhakan  thanks for u r reply..
