### ISSUE TITLE
Expose details of PoijiRowSpecificException

### ISSUE THREAD

**Issue by virtual-machinist** [ozlerhakan/poiji#308]
Hi!

First of all, thank you for a wonderful library, the most feature-rich for parsing Excel spreadsheets I could find out there.

I have however a small feature request. When parsing the spreadsheet I must report all errors due to required missing data to an API. `PoijiRowSpecificException` does collect everything I want, but as a concatenated string. Parsing it back from the error message feels weird.

Can we expose the constructor parameters of `PoijiRowSpecificException` as properties in addition to the message?

**Comment by virtual-machinist** [comment]
As a matter of fact, I could also use additional details in `com.poiji.exception.HeaderMissingException`, i.e. 
`missingExcelCellHeaders` and `missingExcelCellNameHeaders` used to generate the message in [AnnotationUtil:80](https://github.com/ozlerhakan/poiji/blob/5facb7e55675f0d0703b8f56ee947cbfb6143998/src/main/java/com/poiji/util/AnnotationUtil.java#L80).

@ozlerhakan, what do you think, is this something I can also add to the PR?

**Comment by ozlerhakan** [comment]
Hey @virtual-machinist , 

Thank you for contributing Poiji! I highly appreciate!
 
Please go ahead!

**Comment by virtual-machinist** [comment]
@ozlerhakan, thanks, my pleasure.

I've updated the PR, both properties of `HeaderMissingException` are now exposed as well.

**Comment by ozlerhakan** [comment]
Hi @virtual-machinist , after the release deployment, you can use your enhancement with 4.4.0 :), thank you!

**Comment by virtual-machinist** [comment]
Woah, that was fast. :) Thanks lots, @ozlerhakan !
