### ISSUE TITLE
Unable to Retrieve the values from excel sheet properly

### ISSUE THREAD

**Issue by venkateshhvp** [ozlerhakan/poiji#312]
Hi @ozlerhakan ,

I implemented the same way as you mentioned in the documentation, but I m not able to get the values properly.
Instead of the excel values, I m getting only the instance like this [ExcelPoijiDemo@71ae31b0, ExcelPoijiDemo@4ba534b0]

Main.java
		List<ExcelPoijiDemo> demo = Poiji.fromExcel(new File("inputdata.xlsx"), ExcelPoijiDemo.class);	
		System.out.println(demo);

ExcelPoijiDemo.java
@ExcelSheet("Sheet1")
public class ExcelPoijiDemo {
	
	@ExcelCellName("name")
	private String name;
	
	@ExcelCellName("department")
	private String department;
	
}

POM.xml
![image](https://github.com/ozlerhakan/poiji/assets/41261297/89c36dac-7138-4505-aa63-d6ac898737d3)

![image](https://github.com/ozlerhakan/poiji/assets/41261297/933e816a-74e7-43b7-8f5b-4fd229831882)

**Comment by ozlerhakan** [comment]
Hi @venkateshhvp ,

This is the way how we can retrieve rows from an excel file:

```
PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings()
        .addListDelimiter(";") (1)
        .build();
List<Employee> employees = Poiji.fromExcel(new File("employees.xls"), Employee.class, options);
// alternatively
InputStream stream = new FileInputStream(new File("employees.xls"))
List<Employee> employees = Poiji.fromExcel(stream, PoijiExcelType.XLS, Employee.class, options);

employees.size();
// 3
Employee firstEmployee = employees.get(0);
// Employee{rowIndex=1, employeeId=123923, name='Joe', surname='Doe', age=30, single=true, emails=[joe@doe.com, joedoe@gmail.com], biils=[123,10, 99.99]}

```

**Comment by venkateshhvp** [comment]
Hi @ozlerhakan,my output is different than what you showed. Please check and confirm if anything is wrong from my side.

PROJECT STRUCTURE
![image](https://github.com/ozlerhakan/poiji/assets/41261297/3b03e491-3e56-44c6-9131-06e8fa62d32d)

MAIN FILE
![image](https://github.com/ozlerhakan/poiji/assets/41261297/06757b02-f700-4fdf-a87c-ea5e7c44e98e)

POJO FILE
![image](https://github.com/ozlerhakan/poiji/assets/41261297/ddc86319-2dd3-4c50-9bb5-abdacfd3ec70)

OUTPUT
![image](https://github.com/ozlerhakan/poiji/assets/41261297/da9bb511-22b4-465b-9f7a-5947393c8589)

INPUT EXCEL
![image](https://github.com/ozlerhakan/poiji/assets/41261297/09256272-7725-4740-96b4-8a92db8215da)

I tried giving (1) as attached, but not sure what it was meaning and got syntax error.
![image](https://github.com/ozlerhakan/poiji/assets/41261297/c3bfecac-9d3f-4040-a8fb-4ac34a3aa0a3)
