### ISSUE TITLE
issue with parsing to String value that is Double or BigInteger

### ISSUE THREAD

**Issue by dashayakubovich** [ozlerhakan/poiji#318]
Hi! @ozlerhakan 
I use poiji and faced with the following issue:
can't parse to java String
<img width="345" alt="image" src="https://github.com/ozlerhakan/poiji/assets/170344873/83e500a1-a1f8-469b-82d3-ee6b1cdb5885">
<img width="351" alt="image" src="https://github.com/ozlerhakan/poiji/assets/170344873/4c57ca30-8be4-4f0a-861a-0bd42ac8a624">
but xlsx file has the following values
<img width="601" alt="image" src="https://github.com/ozlerhakan/poiji/assets/170344873/8e47f2b1-4971-449c-8bf4-cf545ed5b4c2">
Can you help me understand what I am doing incorrectly?

**Comment by ozlerhakan** [comment]
Hi @dashayakubovich , 

Hmm interesting... could you share your excel file with me, if you don't mind?

**Comment by dashayakubovich** [comment]
[example.xlsx](https://github.com/ozlerhakan/poiji/files/15412955/example.xlsx)
@ozlerhakan hi, sure

**Comment by ozlerhakan** [comment]
Apparently, in your excel file, you have predefined special formats for numbers for your cells. The problematic format number that your excel is using by default is 165. We need to remove that format from the style table using the following approach in Poiji:

```
        PoijiNumberFormat numberFormat = new PoijiNumberFormat();
        numberFormat.putNumberFormat((short) 165, "");
        PoijiOptions poijiOptions = PoijiOptions.PoijiOptionsBuilder.settings()
        .poijiNumberFormat(numberFormat)
        # rest of your options
        # ...
        .build();
```

I hope it helps your problem. You can check how to modify number formats in your excels at https://github.com/ozlerhakan/poiji?tab=readme-ov-file#modify-cells-formats

**Comment by dashayakubovich** [comment]
@ozlerhakan how to understand index number?

**Comment by ozlerhakan** [comment]
You can check what format number each cell is using with https://github.com/ozlerhakan/poiji?tab=readme-ov-file#debug-cells-formats and once you have the number, you can update it accordingly.
