### ISSUE TITLE
Incorrect Date Parsing for mm-dd-yyyy Format, Defaults to Current Date

### ISSUE THREAD

**Issue by Bucephalus-lgtm** [ozlerhakan/poiji#319]
I have an Excel file where I have set a date field in the `mm-dd-yyyy` format. When I try to parse this file using `Poiji.fromExcel(<file_path>, Class<T>)` in my Java Spring Boot project, the date field is set with the value of the current date instead of the actual date from the file. I suspect that this issue arises because Poiji uses the default `dd/M/yyyy` format for date parsing.

Is there a way to make Poiji handle date fields more flexibly? Ideally, as long as the field type is marked as `Date`, the format of the date should not matter. Can Poiji be configured to recognize and correctly parse various date formats without explicitly specifying each one?

Thank you for your assistance.

**Comment by ozlerhakan** [comment]
Hi @Bucephalus-lgtm ,

You can check what format number for the date cell is using with https://github.com/ozlerhakan/poiji?tab=readme-ov-file#debug-cells-formats and once you have the number, you can update with this step: https://github.com/ozlerhakan/poiji?tab=readme-ov-file#modify-cells-formats.

**Comment by Bucephalus-lgtm** [comment]
Hello @ozlerhakan Thanks for the quick response!
I understand that but the twist lies here: 
I have the date attribute with `LocalDate` datatype in my model class. I know, changing the field to `String` parses dates correctly, indicating an issue with Poiji's default `dd/M/yyyy` format.

Moreover, I must keep the date fields as `LocalDate` in my model class because my entity class uses `LocalDate`, and I need to save the data to a DB. Is there a way to make Poiji flexibly handle various date formats without explicit specification, ensuring correct parsing for `LocalDate` fields?

Thank you for your assistance.

**Comment by ozlerhakan** [comment]
Consider using [dateTimeFormatter](https://github.com/ozlerhakan/poiji/blob/master/src/main/java/com/poiji/option/PoijiOptions.java#L375) to change the default format in your own PoijiOptions object.

**Comment by Bucephalus-lgtm** [comment]
Correct, closing the issue hereby.
