### ISSUE TITLE
Can I map only the first 10 rows?

### ISSUE THREAD

**Issue by ThanosFisherman** [ozlerhakan/poiji#32]
I need to read only the first 10 rows from an excel of 1 million rows and this needs to be done fast. Can I map only the first 10 rows in a streaming fashion?

**Comment by ThanosFisherman** [comment]
Hi @ozlerhakan yes that would help. Thanks

**Comment by hariprasadkc** [comment]
@ozlerhakan Can I look into this ?

**Comment by ozlerhakan** [comment]
sure @hariprasadkc :)

**Comment by jigarWala** [comment]
Hey @ozlerhakan  I would like to work on this issue.
