### ISSUE TITLE
getting cast exception in case if fields are wrapper calsses

### ISSUE THREAD

**Issue by vikrantch-hk** [ozlerhakan/poiji#35]
@ozlerhakan hi is there a way to use wrapper classes for fields lets say Long or Double. I was trying with Long field and getting cast exception, when I changed field type to primitive it worked properly. Is there a way I can use Wrapper classes of primitive types

**Comment by ozlerhakan** [comment]
Hi @vikrantch-hk ,

Currently, poiji only supports primitive types. We can find a proper way to make this possible though.

**Comment by vikrantch-hk** [comment]
@ozlerhakan can you suggest where should I look into if I want to try these changes

**Comment by ozlerhakan** [comment]
I'll release a new version about that purpose in one hour @vikrantch-hk

**Comment by ozlerhakan** [comment]
If what I am thinking will work correctly, we should only look at the `Casting#castValue` method to add wrapper classes next to primitive types.

**Comment by ozlerhakan** [comment]
You can use 1.12 @vikrantch-hk  now

**Comment by vikrantch-hk** [comment]
@ozlerhakan thanks :)

**Comment by ozlerhakan** [comment]
Great thanks @vikrantch-hk
