### ISSUE TITLE
When any two rows has same data it only adds one java object in list of POJO

### ISSUE THREAD

**Issue by gajeralalji** [ozlerhakan/poiji#37]
You can replicate it by reading a file which has 2 duplicate rows.

**Comment by ozlerhakan** [comment]
Hi @gajeralalji ,

I haven't produced the error. Could you share your file?

**Comment by gajeralalji** [comment]
Sorry My bad, I had this setting resulting to ignore data row.
  PoijiOptions options = PoijiOptionsBuilder.settings(2).build();
Closing the issue
