### ISSUE TITLE
java.lang.NoSuchFieldError: CREATE_NULL_AS_BLANK 

### ISSUE THREAD

**Issue by huangfuconghhh** [ozlerhakan/poiji#4]
The excel is test.xlsx:
|campusid | campusname | campusnumber | campusarea | campusaddress
|ca111111 | campus1| 301 | 5000 | address1
|ca111112 | campus2 | 302 | 4000 | address2
|ca111113 | campus3 | 303 | 3000 | address3
|ca111114 | campus4 | 304 | 2000 | address4
|ca111115 | campus5 | 305 | 500 | address5
|ca111116 | campus6 | 306 | 1000 | address6
And the pojo code is also right.
        @ExcelCell(0)
    private String campusid;
	@ExcelCell(1)
    private String campusname;
	@ExcelCell(2)
    private Integer campusnumber;
	@ExcelCell(3)
    private Float campusarea;
	@ExcelCell(4)
    private String campusaddress;

I check it for many times but can find the reason.

**Comment by huangfuconghhh** [comment]
I can runmy testcase correctly in the source code.
But when i import it by maven ,it failed.
And when i change the  Row.MissingCellPolicy.CREATE_NULL_AS_BLANK to Row.CREATE_NULL_AS_BLANK in isRowEmpty(), it worked.
I am so confused.

**Comment by ozlerhakan** [comment]
Hi @huangfuconghhh ,

Do you use the Poiji's dependency of Apache POI right? By default, poiji uses Apache POI 3.15

**Comment by ozlerhakan** [comment]
They say that `Row.CREATE_NULL_AS_BLANK` will be deprecated  as of POI 3.15-beta2, scheduled for removal in 3.17 - use the MissingCellPolicy enum instead

**Comment by huangfuconghhh** [comment]
I change the poi verson  from 3.9 to 3.15 and it works. Thank you. It helps me a lot.

**Comment by ozlerhakan** [comment]
Great!, you don't need to include apache poi dependency, just import poiji , it will include apache poi as well.

**Comment by vashe9** [comment]
I have the same error, I have poi imported only via poiji but I still get this error for xls files, xlsx files give another error.
