### ISSUE TITLE
Column handling possibilities

### ISSUE THREAD

**Issue by brobee** [ozlerhakan/poiji#40]
Hi Hakan,

1. question: I have an excel sheet, but in some cases, I need to avoid not only the first row, I need to skip the first 3 row. PoijiOptions is ok with it? How can use it?

2. question: what if I have 5 column like: id|name|gender|age|address and I need to parse in one case only the age and address? How can I do that with cell position number? Or in this case, I need to use ExcelCellName? I didn't find the example for it.

My idea would be: I have a person xlsx, so if I use excelCelName and not position, I can use custom getters like, Person person = person.getId("id"), person.getName("Smith"), person.getGender("male")? Do I need to implement the custom getters? It would be easier to use getId simply.

3. Question: Can I use List and the cell contains several items with comma? I really need to have the ability to fetch everything from the cell and if I have 3 integer in the cell divided by , it should be handled as a list.

@ExcelName("whatever")
List<String> whateverList;

Many thanks and keep up the good work!

**Comment by ozlerhakan** [comment]
Hi @brobee ,

> question: I have an excel sheet, but in some cases, I need to avoid not only the first row, I need to skip the first 3 row. PoijiOptions is ok with it? How can use it?

To ignore the first 3 rows, you can use PoijiOptions to set the required number as

```
# to skip header + 3 rows (that you want)
PoijiOptions options = PoijiOptionsBuilder.settings(4).build();
```
> question: what if I have 5 column like: id|name|gender|age|address and I need to parse in one case only the age and address? How can I do that with cell position number? Or in this case, I need to use ExcelCellName? I didn't find the example for it.

| id        | name           | gender  |
| ------------- |:-------------:| -----:|
| 123      | Joe | Male |
| 3432      | Paul      |   Male |
| 3842 | Doe      |    Male |

If you have a table like above, and you only want to get the name from the excel file, you can only add the poiji annotation to have these data:

```
public class {

    @ExcelCell(1)
    private String name;

   # getter/setter of name is for your design pattern
}
```

Poiji doesn't need getters/setters to map the excel data into a Java object.

>Many thanks and keep up the good work!

Thank you so much :)

**Comment by brobee** [comment]
Thank you for your answer!

1. question: got it, thanks!

2.question: What if I want to get the id and gender? So I need to skip few columns? I just use excelCell(1) for id and ExcelCell(2) for gender and I skip the name?

And what if I want to get the java object not by index, by getters like getGender?

My other question, is it possible to use List, not single element? What if I have 3 integer in one cell divided by comma? I can implement the split, but I need that object as a list.

Thanks!

**Comment by ozlerhakan** [comment]
> 2.question: What if I want to get the id and gender? So I need to skip few columns? I just use excelCell(1) for id and ExcelCell(2) for gender and I skip the name?

In the example table, ExcelCell(0) will give you the id column and ExcelCell(2) gives you the gender column. As long as you mention ExcelCell in your fields you can map the corresponding columns. 

> And what if I want to get the java object not by index, by getters like getGender?

If I understand your question, you can create getter and setter for each field but poiji injects the excel data to fields without using their getters/setters methods.

> My other question, is it possible to use List, not single element? What if I have 3 integer in one cell divided by comma? I can implement the split, but I need that object as a list.

Hmm, currently, poiji doesn't support this behavior but we can try to implement it. For example, as your pointed out, If we have 3 integers in one cell divided by comma, we can tell poiji to split data using the delimiter and create a list based on the value type.

**Comment by brobee** [comment]
> If I understand your question, you can create getter and setter for each field but poiji injects the excel data to fields without using their getters/setters methods.

Actually yes. Poiji parse the excel and put in an object but I'd like to use custom getters like getId, getName. So If I parse the excel using:

List<TestObject> tcDataSet = Poiji.fromExcel(new File("src/test/resources/testData/testData.xlsx"),TestObject.class);

tcDataSet.get(0).getName should work. is that correct?


List support would be awesome, in this case we could use the lib for our project! Thanks for your awesome support!

**Comment by ozlerhakan** [comment]
> tcDataSet.get(0).getName should work. is that correct?

Yes, as long as you created a getter method for the name field, you'll access the data using the getter method.

> List support would be awesome, in this case we could use the lib for our project! 

I keep this in my mind, Thank you @brobee
