### ISSUE TITLE
Object contains list of objects inside

### ISSUE THREAD

**Issue by surimogili** [ozlerhakan/poiji#41]
For example if I want to read excel where I have objects inside one object
Like
Inside Employee
I have Address object with different fields
or for example if  I have two address for one employee
In this case how we can handle this?
My model looks like this
Employee
{
List<Address> addressList;
}

Address
{
String pincode;
}

Can you pls help how todo using poiji

**Comment by ozlerhakan** [comment]
Hi @surimogili ,

Does each address exist in a different column? 

| Name        | Adress 1           | Address 2  |
| ------------- |:-------------:| -----:|
| Joe     | address1 | address2 |
| Paul      | address1      |   $address2 |

**Comment by surimogili** [comment]
Yes, exactly. Not only address, we have more such repetitive columns.

**Comment by ozlerhakan** [comment]
If your excel columns are fixed, you can create an entity class like below:

public class Person {

    @ExcelCell(0)
    private String name;

    @ExcelCell(1)
    private String address1;

    @ExcelCell(2)
    private String address2;

}

**Comment by surimogili** [comment]
No, what I want exactly is
Inside Person, I have list of address objects. For example below are the column names
Name, address1, city1, state1, pincode1, address2, city2, state2, pincode2;

My Model class will look like this
Person
{
String name;
List<Address> addressList;
}

In address class I should have like this

Address
{
String address;
String city;
String state;
String pincode;
}

**Comment by ozlerhakan** [comment]
poiji doesn't support such approach @surimogili
