### ISSUE TITLE
Adding support for java.time.LocalDate and Enums

### ISSUE THREAD

**Issue by Ramgarr** [ozlerhakan/poiji#42]
Hello

Love this package !

I'd love it even more if it could support java.time.LocalDate and Enums !

Do you think adding this could be of interest ? I'd be willing to do it.

**Comment by ozlerhakan** [comment]
Hi @Ramgarr ,

> Do you think adding this could be of interest ?

Sounds good, I think. In a later version, probably Poiji only supports Java 8 and newer. We can then support `java.time.LocalDate` for sure.

**Comment by Ramgarr** [comment]
I created a pull request for this, feel free to use it !

https://github.com/ozlerhakan/poiji/pull/45

Thanks for the lib, it works great !

**Comment by ozlerhakan** [comment]
Thanks again @Ramgarr, 1.15 is available now.
