### ISSUE TITLE
Skip every second row support

### ISSUE THREAD

**Issue by brobee** [ozlerhakan/poiji#44]
Hi Hakan,

can we configure poiji in order to skip every second row during the parsing?

headerRow: using poiji options, skip it (It is ok)
valid dataRow: parse
some additional info in a new row: Do not parse it.
valid dataRow: Parse
additionalInfoRow: do not parse it
etc.

Thanks!

**Comment by ozlerhakan** [comment]
Hi @brobee ,

Hmm, this feature doesn't exist right now. We need to implement a skip mechanism to do that.

**Comment by AvudaiM** [comment]
@ozlerhakan I would like to take this up.

**Comment by ozlerhakan** [comment]
sure @AvudaiM :)

**Comment by jigarWala** [comment]
Hey @ozlerhakan  can I take this one, If @AvudaiM  is not ?

**Comment by ozlerhakan** [comment]
do you look at this issue @jigarWala ?

**Comment by jigarWala** [comment]
Hi @ozlerhakan, nope I am yet to look into this issue.

I had initially thought of splitting this feature by specifying 2 options(in poijioptions)

1. Rows to read interval
2. Rows to skip after that read

Above points take into account that skip, and limit checks are done

Default values
Rows to read interval = infinite
Rows skip interval = 0

**Comment by jigarWala** [comment]
I am working on this one, I'll raise PR by this weekend :smile:

**Comment by ozlerhakan** [comment]
we can think of this option later again when we get more requests
