### ISSUE TITLE
Blank numeric cells are zero rather than null

### ISSUE THREAD

**Issue by alexandrarprice** [ozlerhakan/poiji#47]
Hello!
I'm currently working on a project where we are using your library to parse an xls into an object and then doing some validation against that object. 

We are running into an issue where when a numeric cell is blank, after parsing using Poiji, when we check the value of that field it is 0 -- this makes it hard for us to determine if the field actually contained zero or was blank/empty. We need to be able to treat zeros and empty fields differently.

We're wondering why Poiji sets a blank numeric field as zero rather than something like null that would indicate a missing value?

Thanks!

**Comment by ozlerhakan** [comment]
Hi @alexandrarprice ,

Have you tried to initialize the field to null or other values like:

```
@ExcelCell(0)
private Integer total = 0;

@ExcelCell(1)
private Float total = null;
```

You can use wrapper classes of primitive types with poiji.

**Comment by alexandrarprice** [comment]
Hey, thanks so much for the quick response!
We just tried this and we found it was still being overwritten as zero. If this isn't the intended behavior, we'd be happy to try our best shot at a PR!
Thanks!

In case it helps at all, here's a sample of what our object looks like:
```
 @ExcelCellName("Cost")
  private Double cost = null;
```
We tried it with @ExcelCell as well, same results.
Tagging teammate @mindyor as I'll be headed out on vacation this afternoon. Thanks!

**Comment by ozlerhakan** [comment]
Hmm, I can also investigate if you have a test excel file @alexandrarprice

**Comment by mindyor** [comment]
Thanks for helping us take a look!

Uploading a zip ([Archive.zip](https://github.com/ozlerhakan/poiji/files/2255156/Archive.zip)) with two toy files:
- sample.xlsx works, does initialize Cost automatically
```
@ExcelCellName("Cost")
private Double cost;
```
or to a number should we choose to. 
```
@ExcelCellName("Cost")
private Double cost = 12d;
```

- sample.xls shows us 0 regardless of what we initialize cost to.

**Comment by mindyor** [comment]
Using PoijiOptions.preferNullOverDefault didn't seem to help :/

**Comment by ozlerhakan** [comment]
Hi @mindyor ,

Could you try the 1.16 snapshot for this case:

```
<dependency>
  <groupId>com.github.ozlerhakan</groupId>
  <artifactId>poiji</artifactId>
  <version>1.16-SNAPSHOT</version>
</dependency>
```

**Comment by mindyor** [comment]
Hm, I seem unable to pull down that snapshot.

https://jcenter.bintray.com/com/github/ozlerhakan/poiji/ and https://repo.maven.apache.org/maven2/com/github/ozlerhakan/poiji/ only go up to 1.15.

**Comment by ozlerhakan** [comment]
You can see the snapshot over there: https://oss.sonatype.org/content/repositories/snapshots/com/github/ozlerhakan/poiji/

You should mention this url in your pom file as a reporsitory. You can look at this gist for details: https://gist.github.com/ktuukkan/8cf2de1e915185118c60

**Comment by mindyor** [comment]
Ah, got it. Thank you.

Without preferNullOverDefault(true), the same behavior persists (defaults to 0) for XLS
With preferNullOverDefault(true), String cells are null for both XLS and XLSX.

**Comment by ozlerhakan** [comment]
So this is what you want? @mindyor

**Comment by mindyor** [comment]
Sorry for not being clearer.
No, it looks like this change breaks the existing functionality for String.

**Comment by ozlerhakan** [comment]
But if we use `preferNullOverDefault(true)` String values should be null. Otherwise, String fields will be assigned to an empty String. What do you think?

**Comment by mindyor** [comment]
I agree, but even cells that are non-empty are being parsed in as null. Are you able to replicate this?

**Comment by ozlerhakan** [comment]
hmm, interesting, do you have a mockup excel ?

**Comment by mindyor** [comment]
The excel in the zipfile attached above (sample.xls in Archive.zip) should work.

**Comment by ozlerhakan** [comment]
You can try again the same snapshot, I think I have fixed that problem.

**Comment by mindyor** [comment]
Yes!! Looks good 👍 !!

**Comment by ozlerhakan** [comment]
1.16 is now available @mindyor @alexandrarprice

**Comment by alexandrarprice** [comment]
Awesome, thank you so much!!
