### ISSUE TITLE
Excel date import format error

### ISSUE THREAD

**Issue by fmarazita** [ozlerhakan/poiji#48]
Hi @ozlerhakan 

I think I have found a little bug for the Excel Type excel.
If the column in the excel is type "Excel Date" and not "String" the tool import not correctly the date.

For example try to import the following excel (sheet1):
https://www.esma.europa.eu/sites/default/files/template_-_si_calculations.xlsx

for the first row I have:
If you use in the Pojo:
Column(0) String -> 1/1/18
or
Column(0) java.util.date -> 1 jan 0018

Maybe I tried in not correct way.

Thanks
Fabrizio

**Comment by ozlerhakan** [comment]
I will add an option to set a custom date formatter, so that you can add your formatter to handle different date formats @fmarazita

**Comment by ozlerhakan** [comment]
Hi @fmarazita ,

You can now use 1.15 to create a custom date time formatter. In your case, you should create a datetime formatter like:

```
final DateTimeFormatter formatter = new DateTimeFormatterBuilder()
                .appendPattern("M/d/")
                .appendValueReduced(ChronoField.YEAR_OF_ERA, 2, 2, LocalDate.now().minusYears(80)).toFormatter();

        PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings().sheetIndex(1).dateTimeFormatter(formatter).build();

        List<Calculation> calculations = Poiji.fromExcel(new File(path), Calculation.class, options);

```

**Comment by fmarazita** [comment]
I will try when maven central will be updated. Thanks a lot!
