### ISSUE TITLE
Dex cannot parse version 52 byte code.

### ISSUE THREAD

**Issue by luangs7** [ozlerhakan/poiji#5]
Log:
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by ozlerhakan** [comment]
Hi @luangs7 ,

Do you mean that we should compile the framework with Java 7?

**Comment by luangs7** [comment]
@ozlerhakan I would like to :(

**Comment by ozlerhakan** [comment]
I will do it :)) , just I must sure that I don't use any Java 8 features on it

**Comment by ozlerhakan** [comment]
Hi @luangs7 ,

as of v1.3 it is compatible with Java 7 and above, https://oss.sonatype.org/content/groups/public/com/github/ozlerhakan/poiji/

**Comment by luangs7** [comment]
Thanks mate! @ozlerhakan 
But I found this error: 

> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/poi/ss/usermodel/DataFormatter;

Did I do something wrong?

**Comment by ozlerhakan** [comment]
Hmm interesting, this should exist in the main org.apache.poi package. Did you check this class whether it is really exists or not?

**Comment by luangs7** [comment]
@ozlerhakan Yeah, I found `import org.apache.poi.ss.usermodel.DataFormatter;` in Unmarshaller class.

**Comment by ozlerhakan** [comment]
so any failure happens again?

**Comment by ozlerhakan** [comment]
I mean in your project, is Apache poi  dependency imported into you deps correctly?

**Comment by luangs7** [comment]
@ozlerhakan Yes, this is the log:

> Process: br.com.luan2.xlsxreader, PID: 7520
                                                                       java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/poi/ss/usermodel/DataFormatter;
                                                                           at com.poiji.internal.marshaller.Unmarshaller.<init>(Unmarshaller.java:27)
                                                                           at com.poiji.internal.marshaller.Deserializer.instance(Deserializer.java:16)
                                                                           at com.poiji.internal.Poiji.deserializer(Poiji.java:36)
                                                                           at com.poiji.internal.Poiji.fromExcel(Poiji.java:28)

**Comment by luangs7** [comment]
I found the problem.
I forgot to import this `JAR`: `poi-ooxml-schemas`

But is showing another error again, but my mistake I think

**Comment by luangs7** [comment]
This is my code 
`            PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings(1).build();
            List<Employee> employees = Poiji.fromExcel(mFile, Employee.class, options);
            Employee firstEmployee = employees.get(0);`

Showing this error:

>                                                                         java.lang.NoSuchFieldError: No static field CREATE_NULL_AS_BLANK of type Lorg/apache/poi/ss/usermodel/Row$MissingCellPolicy; in class Lorg/apache/poi/ss/usermodel/Row$MissingCellPolicy; or its superclasses (declaration of 'org.apache.poi.ss.usermodel.Row$MissingCellPolicy' appears in /data/app/br.com.luan2.xlsxreader-2/split_lib_dependencies_apk.apk:classes13.dex)

**Comment by samhalpa** [comment]
@luangs7 Did you try it without adding any apache poi dependencies to your pom? Just use only poiji in the pom.

**Comment by ozlerhakan** [comment]
After testing poiji v1.3 , I haven't seen any abnormal issue. as @samhalpa  says, Apache poi is a transitive dependency of Poiji, so you don't need to include Apache Poi. Poiji uses Apache poi 3.15.

**Comment by ozlerhakan** [comment]
I am closing this issue, feel free to leave comments if you have any related problem.
