### ISSUE TITLE
Adding parse exception for java.time.LocalDate 

### ISSUE THREAD

**Issue by phatthinh123** [ozlerhakan/poiji#52]
Hello,
i would love it if it could have some empty check before parse a localdate or exception to return null :+1:  
since you have added it recently 
Thanks you xD

**Comment by ozlerhakan** [comment]
Hi @phatthinh123 ,

Do you mean, if the date cell is empty string, we should return null? Normally, If the date cell is empty (not empty String) the corresponding field value will be null.

**Comment by phatthinh123** [comment]
Yea, atleast some things to handle the exception when using LocalDate 
It stopped running after error when trying to parse an empty String
I didn't talk about Date

**Comment by ozlerhakan** [comment]
I see. I will handle it for 1.16, Thanks @phatthinh123

**Comment by ozlerhakan** [comment]
1.16 is now available @phatthinh123

**Comment by phatthinh123** [comment]
Thanks you
