### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by willpengZH** [ozlerhakan/poiji#53]
Please, help me out. 

Am I using PoijiOptions correctly?

#### Excel
Name|Birthday
--- | ---
Oliver|1982-02-05

#### Entity
```java
StaffBaseInfo {

   @ExcelCellName("Name") private String name;

   @ExcelCellName("Birthday") private java.sql.Date birthday;

}
```

#### Setting date pattern
```java
PoijiOptions options = PoijiOptionsBuilder.settings().datePattern("yyyy-MM-dd").build();
List<StaffBaseInfo> baseInfoList = Poiji.fromExcel(file, StaffBaseInfo.class, options);
```

#### Exception
```java
java.lang.IllegalArgumentException: Can not set java.sql.Date field cn.com.wellcell.entity.hr.StaffBaseInfo.birthday to java.lang.String
```

**Comment by ozlerhakan** [comment]
Hi @willpengZH ,

You used `java.sql.Date ` for birthday field. You should either `java.util.Date ` or `java.time.DateTime ` classes.

**Comment by ozlerhakan** [comment]
Additionally, this statement `PoijiOptions options = PoijiOptionsBuilder.settings().datePattern("yyyy-MM-dd").build();` is only working for a field is of `java.util.Date` type. You need to use `dateTimeFormatter` for `java.time.DateTime`.

**Comment by willpengZH** [comment]
Thanks. 
For my understanding, `java.sql.Date` inherits from `java.util.Date`, which means `java.sql.Date` “is” `java.util.Date`. 
It supposed to be working fine. Right?

**Comment by ozlerhakan** [comment]
Poiji right now doesn't support `java.sql.Date` :/

**Comment by willpengZH** [comment]
Thanks.
Btw, Poiji is awesome though.

**Comment by ozlerhakan** [comment]
Thank you @willpengZH :)
