### ISSUE TITLE
Skip hidden sheets

### ISSUE THREAD

**Issue by Developer-Matt** [ozlerhakan/poiji#55]
Is it currently possible and I just cant see how, or would it be possible to introduce a settings option to ignore all hidden Excel sheets.  
Could not figure out why a excel book I was given would not work and eventually figured out that there where an 4 additional sheets hidden before the one i was viewing and trying to import

Thanks

**Comment by ozlerhakan** [comment]
Do you want to take a specific sheet in your excel? If so, you can use `sheetIndex`:

```
PoijiOptions options = PoijiOptionsBuilder.settings()
                       .sheetIndex(1) 
                       .build();
```
In this case, poiji looks at the *second* sheet of the excel file.

**Comment by Developer-Matt** [comment]
Hi thanks for reply,

Yes I saw the sheet index but unfortunately it wont work for my case as I never know which order the sheets are in.  I just know that I should process the visible ones and ignore all the hidden ones.

I can happily code this up myself and create pull request if you can just point me in the right direction as to where best put this kind of check.

Thanks

**Comment by ozlerhakan** [comment]
Hi @Developer-Matt ,

We handle this process differently for xls and xlsx formats.

You need to look at this part for xls: https://github.com/ozlerhakan/poiji/blob/master/src/main/java/com/poiji/bind/mapping/HSSFUnmarshaller.java#L47

and for xlsx :
https://github.com/ozlerhakan/poiji/blob/master/src/main/java/com/poiji/bind/mapping/XSSFUnmarshaller.java#L51

**Comment by ozlerhakan** [comment]
1.17.0 now allows skipping hidden excel sheets :)

**Comment by ozlerhakan** [comment]
```
PoijiOptions poijiOptions = PoijiOptions.PoijiOptionsBuilder.settings().sheetIndex(2).ignoreHiddenSheets(true).build(); <1>

List<Person> people = Poiji.fromExcel(new File(path), Person.class, poijiOptions);
```
1. Skip all hidden sheets of the excel file and retrieve the data from the 2nd visible sheet
