### ISSUE TITLE
Date pattern Regex

### ISSUE THREAD

**Issue by Developer-Matt** [ozlerhakan/poiji#57]
Hey,  We are having a lot of excel documents being imported with strange date formats, while we can set the date format in the setting options, if the excel document cell value does not match this exact format we sometimes get a strange Date object created, no parse exception is thrown so we don't get null value, we get a strange date.  Would rather have null date then an incorrect date.

Would it be possible to have the ability to specify a regex pattern (yyyy-MM-dd = \\d{4}-\\d{2}-\\d{2}) in setting options so that the date string must match the pattern before it is parsed to a date object.  This way if the document has a date in strange format it can be set to null (if null preferred, or current date).

Do you have any development like this in the pipe line or I can code it up.

Thanks

**Comment by ozlerhakan** [comment]
Hi @Developer-Matt , 

Sorry for my late response about your problem. It looks like you settle it with a new PR Thanks! I will take a look at the changes and notify you
