### ISSUE TITLE
Skip useless lines

### ISSUE THREAD

**Issue by bpenergy** [ozlerhakan/poiji#59]
Hello,

I had some issues to deserialize beans using ExcelCellName.

My Excel file was the following:

![capture](https://user-images.githubusercontent.com/23032559/45652008-3a92cb80-baa1-11e8-9262-9cee935ba9f2.PNG)

In fact, it would be nice to have a similar attribute in loadColumnTitles in order to skip useless lines.

Thank you,

Philippe

**Comment by ozlerhakan** [comment]
Hi @bpenergy ,

Thank you for bringing this up. We should consider this case in a later version.

**Comment by bpenergy** [comment]
Ok thank you,

Philippe

**Comment by ozlerhakan** [comment]
Hi @bpenergy , 

This is available as of 1.19. You can use the `headerStart` method to specify at which the position of the header starts. In the example above, the header starts at 4 (zero-based index).
