### ISSUE TITLE
Cannot read doubles, int, dates from xls file

### ISSUE THREAD

**Issue by ghacupha** [ozlerhakan/poiji#6]
The library seems fine but it can only read values into a bean field which is a string

**Comment by ozlerhakan** [comment]
Hi @ghacupha ,

Have you look at [this test case](https://github.com/ozlerhakan/poiji/blob/master/src/test/java/com/poiji/deserialize/DerializersEmptyCellTest.java), you can be right for dates but int and boolean values are tested. I will look at them again later on.

**Comment by ozlerhakan** [comment]
you can use `Date` as of poiji 1.4 @ghacupha  https://github.com/ozlerhakan/poiji/blob/80395b6ba0b1b415c85d7635d1a1a324e53c7880/src/test/java/com/poiji/deserialize/model/EmployeeExtended.java#L16

**Comment by ghacupha** [comment]
I have done a test and seen that it actually works, both for those primitives and the date. Thanks

**Comment by ozlerhakan** [comment]
cool!
