### ISSUE TITLE
Add Required attribute on annotation ExcelCell and ExcelCellName

### ISSUE THREAD

**Issue by bpenergy** [ozlerhakan/poiji#60]
Hello,

It would be nice to have Required attribute on annotation.

Thank you,

Philippe

**Comment by ozlerhakan** [comment]
Hi @bpenergy ,

Could you please elaborate more about your case?

**Comment by ozlerhakan** [comment]
I didn't understand your point @bpenergy , because you cannot use `@ExcelCell` and `@ExcelCellName` with an empty decleration. That is they require a parameter.

```
    @ExcelCell(3)
    protected String email;

```

**Comment by bpenergy** [comment]
I will use like that:

```
@ExcelCellName(value="Name", required=true)
protected String name;

@ExcelCellName(value="OptionalValue")
protected String optionalValue;

```
And Parser will return a parsing Exception when name attribute is null but not for optionalValue.

**Comment by ozlerhakan** [comment]
feel free to make a PR for this behavior
