### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by siromidz** [ozlerhakan/poiji#61]
when i add implementation 'com.github.ozlerhakan:poiji:1.18.0' to my build.gradle file and sync ,
i get this error:

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.ozlerhakan:poiji:1.18.0.

**Comment by ozlerhakan** [comment]
Hi @siromidz ,

I don't use gradle in my projects. However, when I try it on a new gradle project, it works with the following  `build.gradle` file:

```
plugins {
    id 'java'
}

group 'poijigradle'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile 'com.github.ozlerhakan:poiji:1.18.0'
}

```
