### ISSUE TITLE
Add bigDecimal to castValue

### ISSUE THREAD

**Issue by SimonGW** [ozlerhakan/poiji#62]
Would it be possible to support BigDecimal in Casting.java? I have made a suggestion for the solution here:
`else if (fieldType.getName().equals("java.math.BigDecimal")) {
            o = bigDecimalValue(value, options);
}`
`private BigDecimal bigDecimalValue(String value, PoijiOptions options) {
        try {
            String clean = value != null ? value.replace(",", ".") : "";
            return new BigDecimal(clean);
        } catch (NumberFormatException nfe) {
            if (Boolean.TRUE.equals(options.preferNullOverDefault())) {
                return null;
            }
            return BigDecimal.ZERO;
        }
    }`

Another question; any plan for merging #49 and making a new release? I made the changes locally myself and i can make a more update to date PR if wanted.

**Comment by ozlerhakan** [comment]
Hi @SimonGW ,

Good idea! I will add to support apache poi 4.0.0 as of 1.18.1 and the addition you did here.

**Comment by SimonGW** [comment]
Thank you for the quickly reply, looking forward to version 1.18.1.

**Comment by ozlerhakan** [comment]
I have just published it @SimonGW , once maven repo is updated, you can use 1.18.1. Thank you for your collaboration.
