### ISSUE TITLE
Get cell value, not the formula.

### ISSUE THREAD

**Issue by JoaTorres** [ozlerhakan/poiji#63]
Can i get the cell value instead of the full formula cell as a String? 

![poijihelp](https://user-images.githubusercontent.com/19332008/47171246-d0eb2480-d2cd-11e8-8c4a-8605a10e76f5.png)

**Comment by ozlerhakan** [comment]
Hi @JoaTorres ,

Do you have a sample excel file to try out this case?

**Comment by JoaTorres** [comment]
The sheets im trying to upload are "COBRARPAGARDOC", "DCOBRARPAGARDOC" and "ICOBRARPAGARDOC". 
Ty for the reply.

[Antam 1809 - Prexixion NCR I.xlsx](https://github.com/ozlerhakan/poiji/files/2493579/Antam.1809.-.Prexixion.NCR.I.xlsx)

**Comment by 4sujittiwari** [comment]
@ozlerhakan Has this been fixed..?

**Comment by ozlerhakan** [comment]
no @4sujittiwari
