### ISSUE TITLE
Not working on Android 

### ISSUE THREAD

**Issue by Emeecodes01** [ozlerhakan/poiji#65]
Any time i try to write this library on android it always gives this error and the app crashes
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;

**Comment by ozlerhakan** [comment]
Hi @Emeecodes01 ,

`DateTimeFormatter ` comes with Java 8. Currently, It's not compatible with Android.

**Comment by Emeecodes01** [comment]
OK, so does it mean you can't use this library In Android?

**Comment by ozlerhakan** [comment]
you can use poiji 1.16 or prior versions unless you use Java 1.8

**Comment by ozlerhakan** [comment]
it's a duplicate of #21
