### ISSUE TITLE
Feature Request: Allow for mandatory ExcelCellName fields and throw exception if not present in the input Excel file

### ISSUE THREAD

**Issue by apollo1** [ozlerhakan/poiji#66]
I recently used poiji for extracting the content from an excel file, but I found myself wanting it to do one extra thing. :)

When creating your object model using @ExcelCellName on fields, can we also have an annotation for fields to be required/mandatory.  Then, when deserializing an excel file if the mandatory fields are not present in the Excel file being read, throw a data validation exception.

Thanks,

Jamie

**Comment by ozlerhakan** [comment]
duplicate of #60
