### ISSUE TITLE
Can I use this library to write Data to Excel sheet ?

### ISSUE THREAD

**Issue by nehas510** [ozlerhakan/poiji#69]
I want to write the data to the excel sheet can that be done using this library?

**Comment by ozlerhakan** [comment]
Hi @nehas510 ,

Poiji only transfers the data from excel sheets to java objects.

**Comment by nehas510** [comment]
ok, thnx @ozlerhakan!  Anyways I found this library super easy to use.

Keep up the good work :)

**Comment by vaa25** [comment]
@ozlerhakan could support of excel writing function be added in Poiji?
