### ISSUE TITLE
Import unformatted cells

### ISSUE THREAD

**Issue by pouniok** [ozlerhakan/poiji#7]
Hello,

Is it possible to add an Option to get the unformatted cells values ?

Would be perfect because some users add their own format and I can't parse an unknown format into a Double for example.

Thanks

**Comment by ozlerhakan** [comment]
Hi @pouniok ,

> Would be perfect because some users add their own format and I can't parse an unknown format into a Double for example.

Could you please elaborate it more by giving an example for that case?

**Comment by ozlerhakan** [comment]
I am not sure how to do it right now :/ since poi gives us formatted value directly.

**Comment by pouniok** [comment]
I think we can handle this here : 
https://github.com/ozlerhakan/poiji/blob/81ed126fb9ef7213ed23bcc10006879a3bde75eb/src/main/java/com/poiji/internal/marshaller/Unmarshaller.java#L86

`String value = dataFormatter.formatCellValue(cell);`

Maybe by replacing this line with something like : 
`String value = options.importFormattedCells() ? df.formatCellValue(cell) : cell.getStringCellValue();`

I forked the repo and did the modifications, but I don't know how to compile it and test it. If you can give me some advices to do the testing, I could create a pull request when it's working.

**Comment by ozlerhakan** [comment]
> Maybe by replacing this line with something like : String value = options.importFormattedCells() ? df.formatCellValue(cell) : cell.getStringCellValue();

ah great!

> forked the repo and did the modifications, but I don't know how to compile it and test it. If you can give me some advices to do the testing, I could create a pull request when it's working.

1. clone the project (You actually pass this step :))
2. do your changes
3. add a test case based on your change
4. run `mvn clean install` to see that the tests are pass 

> You did some updates since I forked, so I'll have to check it out before :)

Since 1.5, `.xls` and `.xlsx` structures now use a different path,  your work should only work for the `.xls` file.
