### ISSUE TITLE
Problem converting from excel with version 1.19.1

### ISSUE THREAD

**Issue by fermartinez1** [ozlerhakan/poiji#70]
With last versión (1.19.1) when i do:
products = Poiji.fromExcel(intputStream, PoijiExcelType.XLS, ProductExcelDTO.class);
the return stateman is null but, if the file extension is .XLSX it works fine.
If i do the same with the version 1.13 , its works fine with .XLS and .XLSX .
The DTO haves @ExcelCell and @ExcelCellName.

**Comment by ozlerhakan** [comment]
Hi @fermartinez1 , 
Do you have any error on this?

**Comment by fermartinez1** [comment]
No, only the return is NULL.

**Comment by ozlerhakan** [comment]
I'll look at it, thank you @fermartinez1 .

**Comment by fermartinez1** [comment]
[atach.zip](https://github.com/ozlerhakan/poiji/files/2740753/atach.zip)

Sorry for the delay, i attached the files. If you change file extension to .xlsx it works fine.

**Comment by ozlerhakan** [comment]
I added your test case among the tests so you can try 1.19.2 once it's available on the maven central @fermartinez1

**Comment by ozlerhakan** [comment]
Feel free to add your comments if you have questions for this issue, I close it for now
