### ISSUE TITLE
IndexOutOfBoundsException when using fromExcel

### ISSUE THREAD

**Issue by VanOvermeire** [ozlerhakan/poiji#72]
Hi,

When I try to use your library on an excel from https://www.uci.org/road/teams, I get the following error:

`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_162] at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_162] at com.poiji.bind.mapping.XSSFUnmarshaller.unmarshal0(XSSFUnmarshaller.java:64) ~[poiji-1.19.2.jar:na] at com.poiji.bind.mapping.XSSFUnmarshallerStream.returnFromExcelFile(XSSFUnmarshallerStream.java:44) ~[poiji-1.19.2.jar:na] at com.poiji.bind.mapping.XSSFUnmarshallerStream.unmarshal(XSSFUnmarshallerStream.java:36) ~[poiji-1.19.2.jar:na] at com.poiji.bind.Poiji.fromExcel(Poiji.java:218) ~[poiji-1.19.2.jar:na] at com.poiji.bind.Poiji.fromExcel(Poiji.java:191) ~[poiji-1.19.2.jar:na]
...`

The problem seems to be that there are not sheet definitions available in 'getWorkbookData'. Hence, 0 sheets in an arraylist and an index out of bounds for

`WorkBookSheet wbs = sheets.get(sheetCounter); `

Interestingly enough, I did not run into this problem until now, because if I open this excel file with _Numbers_ and export it, everything works - appartently, exporting with _Numbers_ add some sheet metadata.

At a minimum, it would be nice if the library would catch the index out of bounds and say something like "no excel sheets found". 

And for me personally, it would be nice if there was a way to avoid this issue. :) 

Any ideas/suggestions?

**Comment by ozlerhakan** [comment]
Hi @VanOvermeire ,

Thanks for the suggestion. we can show a similar error message in the next release. 

This is, I guess, a rare situation so I need to produce the same case to give some ideas about how to avoid this issue.

**Comment by VanOvermeire** [comment]
Hi @ozlerhakan,

The file in attachment should cause the exception when called with something like:

`Poiji.fromExcel(inputStream, PoijiExcelType.XLSX, CyclistFromFile.class, options);`

The inputstream is from `multipartFile.getInputStream()`.

Our current workaround is to catch the error and return a bad request. It seems likely that the excel is generated by some library that doesn't set the metadata. So if you save/export it using either _Numbers_ or _Excel_, the metadata is updated and the issue is fixed. 

So maybe you could even point the user in that direction? (At the risk of misdirecting them in case there are multiple causes for this error.)

[TeamMembers_ROA_2_7_2019.xlsx](https://github.com/ozlerhakan/poiji/files/2841200/TeamMembers_ROA_2_7_2019.xlsx)

**Comment by ozlerhakan** [comment]
thanks @VanOvermeire , I'll take a look at this case

**Comment by ozlerhakan** [comment]
Hi @VanOvermeire , I'm sorry that I couldn't  look it. Do you have the same problem again?

**Comment by VanOvermeire** [comment]
Haven't touched the code since last year, so the workaround is still in place. I assume the problem is still the same, but did not check.

**Comment by ozlerhakan** [comment]
we display `no excel sheets found` with version 2.6.0.
