### ISSUE TITLE
Parsing the sheet by its name rather than its index

### ISSUE THREAD

**Issue by 4sujittiwari** [ozlerhakan/poiji#73]
Can we currently parse the excel sheet by its name rather than giving its index. 

The problem facing is that the end user has full control over the excel and can modify the sheets index. 

So to parsing an excel by sheet name as Apache poi library provides will add great flexibility for developers.

**Comment by ozlerhakan** [comment]
Hi @4sujittiwari ,

we can find a way to support both options

**Comment by 4sujittiwari** [comment]
Hey @ozlerhakan,

I have just written some lines of code in **XSSFUnmarshaller** which gave me the support for parsing the excel sheet by name. 

`
			String sheetName = options.getSheetName();
			while (iter.hasNext()) {
					try (InputStream stream = iter.next()) {
						if (iter.getSheetName().equalsIgnoreCase(sheetName)) {
						WorkBookSheet wbs = sheets.get(sheetCounter);
						if (wbs.getState().equals("visible")) {
							processSheet(styles, reader, readOnlySharedStringsTable, type, stream, consumer);
							return;
						}
					}
				}
				sheetCounter++;
			}
		`

Please let me know if above code can be used to read excel. 

Thanks

**Comment by ozlerhakan** [comment]
seems good but we need to provide two options, reading data by sheet id and sheet name. @4sujittiwari

**Comment by 4sujittiwari** [comment]
Hello @ozlerhakan 

I have kept both the options to read the excel file.

**Comment by ozlerhakan** [comment]
feel free to make a PR @4sujittiwari

**Comment by 4sujittiwari** [comment]
Sure will make one

**Comment by JENISKAVADIYA** [comment]
Has this been implemented now ?

**Comment by 4sujittiwari** [comment]
Sorry guys, I got caught up into some task. I have implemented it but some tests are failing so I am making sure everything works fine after this change.
