### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by vandanagoel** [ozlerhakan/poiji#75]
Can a Excel CellValue be mapped to an enum?

**Comment by vandanagoel** [comment]
Looking at code it seems   
    private Object enumValue(String value, Class type) {
        return Arrays
                .stream(type.getEnumConstants())
                .filter(o -> ((Enum) o).name().equals(value))
                .findFirst()
                .orElse(null);
    }


name of enum is used.  Using toString gives more flexibility.

**Comment by ozlerhakan** [comment]
yes @vandanagoel

**Comment by ozlerhakan** [comment]
Do you mean this: `((Enum) o).toString().equals(value))` @vandanagoel ?

**Comment by vandanagoel** [comment]
yes  thats what I mean.   @ozlerhakan

**Comment by ozlerhakan** [comment]
if you want, you can make a PR for that @vandanagoel
