### ISSUE TITLE
Convert excel columns to Java objects instead of rows

### ISSUE THREAD

**Issue by JENISKAVADIYA** [ozlerhakan/poiji#76]
We have excel sheet generated from business (external web application) that generates excel sheets with test headers specified in columns and test data column wise. poiji is missing populating Java from column instead of existing support of rows data.

**Comment by ozlerhakan** [comment]
Hi @JENISKAVADIYA , 

Feel free to implement this feature, It would be nice to have it :)

**Comment by ozlerhakan** [comment]
once you add this change, we can open it again
