### ISSUE TITLE
Can't parse date to either LocalDate or Date or String correctly

### ISSUE THREAD

**Issue by vmasule** [ozlerhakan/poiji#78]
**I have below format date in excel.**

Original DOB

30/07/1969
03/10/1984
29/09/1955

How to parse these to `yyyy-MM-dd`?. I am getting no error message here.

**What I have tried**

```
   DateTimeFormatter ISO_DATE_TIME = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            PoijiOptions options = settings().datePattern("yyyy-MM-dd").dateTimeFormatter(ISO_DATE_TIME).dateLenient(true).build();
```

**Comment by ozlerhakan** [comment]
Hi @vmasule ,

It looks like the pattern you want doesn't match the input, you should try something 
```
DateTimeFormatter format = new DateTimeFormatterBuilder()
                .appendPattern("dd/M/yyyy").
PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings().dateTimeFormatter(format).build();
```

**Comment by ozlerhakan** [comment]
Note that `dateTimeFormatter ` only works for fields whose type is `java.time.LocalDate`

**Comment by vmasule** [comment]
@ozlerhakan, Sorry it didn't work for me. Is it because I have calculated(formula) on that column? 
Is there a way I can enforce to evaluate formal on the column?

**Comment by ozlerhakan** [comment]
do you have a mock excel? @vmasule I can try on it
