### ISSUE TITLE
Accessing data from different SpreadSheet

### ISSUE THREAD

**Issue by vpradeepkumar94** [ozlerhakan/poiji#8]
Hi,
How to access the data from different sheets in same excel ?

**Comment by ozlerhakan** [comment]
Hi @vpradeepkumar94 ,

Currently we can only get the first (default) sheet of an excel file. However, we can add a sheet index option to `PoijiOptions` to look at different sheet.

**Comment by ozlerhakan** [comment]
you can use PoijiOptions with the sheet index option as of 1.5 like below:

```
PoijiOptionsBuilder.settings()
                    .skip(1)
                    .datePattern("dd/mm/yyyy")
                    .sheetIndex(1).build(); 
```

You pick the **second** sheet of the excel. @vpradeepkumar94

**Comment by vpradeepkumar94** [comment]
Hi,
Thanks for the update :)
