### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.commons.compress.utils.InputStreamStatistics

### ISSUE THREAD

**Issue by ghacupha** [ozlerhakan/poiji#83]
Just ran into that exception, when running version 1.20.0. Not sure how, but my guess is that the POI you are using which is POI version 4 requires the apache compression library version 1.18 (the earlier versions do not have the InputStreamStatistics library). Immediately I added that into the project, the problem was gone, and poiji started working just as reliably as before. 
I with respect submit this PR for your consideration: #82

**Comment by ghacupha** [comment]
Should you wish to not include it in the lib, you could add a note for users to add this version of apache compress into their project.

**Comment by ozlerhakan** [comment]
Hi @ghacupha , I am closing this issue for now, feel free to leave a comment
