### ISSUE TITLE
Parsing decimal value in other locales than "en" produces 0.0

### ISSUE THREAD

**Issue by breucode** [ozlerhakan/poiji#91]
First of all, thank you for such a great library with lots of features, which are really helpful.

The following self-contained example demonstrates the error quite comprehensively:
https://gitlab.com/breucode/poiji-decimal-parsing-error

Just have a look at both of the unit tests. The difference in these tests is, that I try to parse the same file with different default locales.

When the locale is set to GERMANY, the value poiji produces is 0.0 instead of the 1.5 in the excel sheet. When the locale is set to US however, the cell is parsed correctly.

**Comment by ozlerhakan** [comment]
Hi @breucode ,

Thank you for your support :)

do you have a solution to fix this problem?

**Comment by breucode** [comment]
Hi @ozlerhakan,

no unfortunately, I don't have a solution for this. The problem is, that the bug I described is quite confusing. I saved an Excel file with a German mac and the file is only correctly parsed with the US locale. A fix in my application would be to hardcode the locale to US, but I wonder what causes the change in behavior, when a different locale is present.

**Comment by Brutus5000** [comment]
Hello there,

I' facing the same issue in my project. A potential solution might be to able to switch between the raw value of the cell and the textual formatted representation. Maybe with an annotation like `@RawValue`

**Comment by hexmind** [comment]
I will fix it

**Comment by hexmind** [comment]
Ready for review. https://github.com/ozlerhakan/poiji/pull/95
