### ISSUE TITLE
Am getting this error that failed to process Poi, its like is not present

### ISSUE THREAD

**Issue by adamwrprogrammertz** [ozlerhakan/poiji#92]
Can you have any way i can use to fix this

**Comment by adamwrprogrammertz** [comment]
This is an error I get when I want to run or build my App
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\Duxte\.gradle\caches\modules-2\files-2.1\org.apache.poi\poi\4.1.0\66ea82c8e7cd87e9ae8bceca45daf01328c8d623\poi-4.1.0.jar

**Comment by ozlerhakan** [comment]
Hi @adamwrprogrammertz ,

you can try other versions of poiji that contains an old poi version

**Comment by adamwrprogrammertz** [comment]
how can i do that can you provide may be a link

**Comment by shubhamR1997** [comment]
If you are doing in android then it's basically the problem in the latest version having an issue with dex. If you will try **version 1.20.0**  then everything seems to works perfectly.  Hope this will solve the issue.
