### ISSUE TITLE
Date is not properly reading.

### ISSUE THREAD

**Issue by dellikilari** [ozlerhakan/poiji#93]
Hi,
Am having the same problem, date is not properly converting.
below are the dates in xlxs file.
5/22/2019
5/24/2019
8/11/2019
And code is below.
PoijiOptions options = PoijiOptions.PoijiOptionsBuilder.settings().datePattern("dd/mm/yy").build();
List projectionVos = Poiji.fromExcel(inputStream, PoijiExcelType.XLSX, User.class, options);

results:
Wed Jan 16 00:02:00 IST 2019
Thu Jan 17 00:04:00 IST 2019
Fri Jan 18 00:11:00 IST 2019

Not sure why its converting to different month and day all together.

Thanks,
Delli/

**Comment by ozlerhakan** [comment]
Hi @dellikilari ,

Perhaps this test can help you out https://github.com/ozlerhakan/poiji/blob/master/src/test/java/com/poiji/deserialize/DeserializersDateRegexTest.java.

**Comment by ozlerhakan** [comment]
feel free to open another issue for that case later
