### ISSUE TITLE
Config from annotation

### ISSUE THREAD

**Issue by mcolak** [ozlerhakan/poiji#94]
Sheetname set through the annotaion, like @ExcellSheetName

**Comment by ozlerhakan** [comment]
Hi @mcolak , you can set a sheet name using `PoijiOptions`

**Comment by mcolak** [comment]
Yes, I can do it. But this will be more effective

**Comment by ozlerhakan** [comment]
feel free to make a PR @mcolak , I would appreciate your work

**Comment by thiyagu-7** [comment]
I would like to work on this for Hacktoberfest if @mcolak is not

**Comment by ozlerhakan** [comment]
Feel free to work on it @thiyagu-7 :)

**Comment by thiyagu-7** [comment]
Hi @ozlerhakan 

Should this annotation be used to indicate which sheet to process (like in `PoijiOptions.sheetName`) or include the current sheet name in the POJO as a field (like `@ExcelRow`)?

If it is the former, should this annotation be a class level annotation?

**Comment by ozlerhakan** [comment]
> if it is the former, should this annotation be a class level annotation?

this should be a class level annotation @thiyagu-7 yes
