### ISSUE TITLE
Date parsing issue

### ISSUE THREAD

**Issue by gomahan** [ozlerhakan/poiji#98]
Date is parsed as two digit year which is causing issue while parsing dates. .

We need to set styles while readying the workbook for the dates

**Comment by jigarWala** [comment]
did you checked PoijiOptions? you can set your own regex/style. Check if it's helpful.

**Comment by gomahan** [comment]
I have tried writing the complete casting class. The problem the date is read from the excel using poi with two digit year . 

As a workaround , I am now changed the column as text in excel and string in poiji annotation and formatted it latter

**Comment by ozlerhakan** [comment]
do you want us to make an update for this case? @gomahan

**Comment by gomahan** [comment]
Actually I think its the issue with Apache poi . 

The solution is described in the below link 

https://stackoverflow.com/questions/53228302/poi-dataformatter-returns-2-digits-year-instead-of-4-digits-year-for-date-cells/53236531#53236531

**Comment by ozlerhakan** [comment]
feel free to open up a PR @gomahan
